'use strict'

var mmmeC19 = require('../../../../../models/smm/fichasMantenimiento/SGMM/ciclico/MMME_C19');

const MMME_C19 = {};

MMME_C19.getMMME_C19Data = async (req, res) => {
    const {id} = req.params;
 
    const maintenance = await mmmeC19.findById(id)
    res.json(maintenance)
};
MMME_C19.editMMME_C19Data = async (req, res) => {
    const { id } = req.params;
    let materiales = {
        numberOfMaterial: req.body.numberOfMaterialInputs,
        arr: req.body.materials
    }
    const MMME_C19 = {
        noInspeccion: req.body.inspeccion || '',
        noTren: req.body.tren || '',
        kilometraje: req.body.distance || 0,
        horaInicio: req.body.startTime || '',
        horaTerminacion: req.body.endTime || '',
 
        //CILINDROS STCRM -700 TE-90 Y TE-95
        tubo5_8m11R: req.body || false,
        tubo5_8m11L: req.body || false,
        tubo5_8m12R: req.body || false,
        tubo5_8m12L: req.body || false,
        tubo5_8m13R: req.body || false,
        tubo5_8m13L: req.body || false,
        tubo5_8m14R: req.body || false,
        tubo5_8m14L: req.body || false,
        tubo5_8m15R: req.body || false,
        tubo5_8m15L: req.body || false,
        tubo5_8m16R: req.body || false,
        tubo5_8m16L: req.body || false,
        tubo5_8m21R: req.body || false,
        tubo5_8m21L: req.body || false,
        tubo5_8m22R: req.body || false,
        tubo5_8m22L: req.body || false,
        tubo5_8m23R: req.body || false,
        tubo5_8m23L: req.body || false,
        tubo5_8m24R: req.body || false,
        tubo5_8m24L: req.body || false,
        tubo5_8m25R: req.body || false,
        tubo5_8m25L: req.body || false,
        tubo5_8m26R: req.body || false,
        tubo5_8m26L: req.body || false,

        tapam11R: req.body || false,
        tapam11L: req.body || false,
        tapam12R: req.body || false,
        tapam12L: req.body || false,
        tapam13R: req.body || false,
        tapam13L: req.body || false,
        tapam14R: req.body || false,
        tapam14L: req.body || false,
        tapam15R: req.body || false,
        tapam15L: req.body || false,
        tapam16R: req.body || false,
        tapam16L: req.body || false,
        tapam21R: req.body || false,
        tapam21L: req.body || false,
        tapam22R: req.body || false,
        tapam22L: req.body || false,
        tapam23R: req.body || false,
        tapam23L: req.body || false,
        tapam24R: req.body || false,
        tapam24L: req.body || false,
        tapam25R: req.body || false,
        tapam25L: req.body || false,
        tapam26R: req.body || false,
        tapam26L: req.body || false,

        empaquem11R: req.body || false,
        empaquem11L: req.body || false,
        empaquem12R: req.body || false,
        empaquem12L: req.body || false,
        empaquem13R: req.body || false,
        empaquem13L: req.body || false,
        empaquem14R: req.body || false,
        empaquem14L: req.body || false,
        empaquem15R: req.body || false,
        empaquem15L: req.body || false,
        empaquem16R: req.body || false,
        empaquem16L: req.body || false,
        empaquem21R: req.body || false,
        empaquem21L: req.body || false,
        empaquem22R: req.body || false,
        empaquem22L: req.body || false,
        empaquem23R: req.body || false,
        empaquem23L: req.body || false,
        empaquem24R: req.body || false,
        empaquem24L: req.body || false,
        empaquem25R: req.body || false,
        empaquem25L: req.body || false,
        empaquem26R: req.body || false,
        empaquem26L: req.body || false,

        piston1m11R: req.body || false,
        piston1m11L: req.body || false,
        piston1m12R: req.body || false,
        piston1m12L: req.body || false,
        piston1m13R: req.body || false,
        piston1m13L: req.body || false,
        piston1m14R: req.body || false,
        piston1m14L: req.body || false,
        piston1m15R: req.body || false,
        piston1m15L: req.body || false,
        piston1m16R: req.body || false,
        piston1m16L: req.body || false,
        piston1m21R: req.body || false,
        piston1m21L: req.body || false,
        piston1m22R: req.body || false,
        piston1m22L: req.body || false,
        piston1m23R: req.body || false,
        piston1m23L: req.body || false,
        piston1m24R: req.body || false,
        piston1m24L: req.body || false,
        piston1m25R: req.body || false,
        piston1m25L: req.body || false,
        piston1m26R: req.body || false,
        piston1m26L: req.body || false,

        capaUm11R: req.body || false,
        capaUm11L: req.body || false,
        capaUm12R: req.body || false,
        capaUm12L: req.body || false,
        capaUm13R: req.body || false,
        capaUm13L: req.body || false,
        capaUm14R: req.body || false,
        capaUm14L: req.body || false,
        capaUm15R: req.body || false,
        capaUm15L: req.body || false,
        capaUm16R: req.body || false,
        capaUm16L: req.body || false,
        capaUm21R: req.body || false,
        capaUm21L: req.body || false,
        capaUm22R: req.body || false,
        capaUm22L: req.body || false,
        capaUm23R: req.body || false,
        capaUm23L: req.body || false,
        capaUm24R: req.body || false,
        capaUm24L: req.body || false,
        capaUm25R: req.body || false,
        capaUm25L: req.body || false,
        capaUm26R: req.body || false,
        capaUm26L: req.body || false,

        vastagom11R: req.body || false,
        vastagom11L: req.body || false,
        vastagom12R: req.body || false,
        vastagom12L: req.body || false,
        vastagom13R: req.body || false,
        vastagom13L: req.body || false,
        vastagom14R: req.body || false,
        vastagom14L: req.body || false,
        vastagom15R: req.body || false,
        vastagom15L: req.body || false,
        vastagom16R: req.body || false,
        vastagom16L: req.body || false,
        vastagom21R: req.body || false,
        vastagom21L: req.body || false,
        vastagom22R: req.body || false,
        vastagom22L: req.body || false,
        vastagom23R: req.body || false,
        vastagom23L: req.body || false,
        vastagom24R: req.body || false,
        vastagom24L: req.body || false,
        vastagom25R: req.body || false,
        vastagom25L: req.body || false,
        vastagom26R: req.body || false,
        vastagom26L: req.body || false,

        tubo1_8m11R: req.body || false,
        tubo1_8m11L: req.body || false,
        tubo1_8m12R: req.body || false,
        tubo1_8m12L: req.body || false,
        tubo1_8m13R: req.body || false,
        tubo1_8m13L: req.body || false,
        tubo1_8m14R: req.body || false,
        tubo1_8m14L: req.body || false,
        tubo1_8m15R: req.body || false,
        tubo1_8m15L: req.body || false,
        tubo1_8m16R: req.body || false,
        tubo1_8m16L: req.body || false,
        tubo1_8m21R: req.body || false,
        tubo1_8m21L: req.body || false,
        tubo1_8m22R: req.body || false,
        tubo1_8m22L: req.body || false,
        tubo1_8m23R: req.body || false,
        tubo1_8m23L: req.body || false,
        tubo1_8m24R: req.body || false,
        tubo1_8m24L: req.body || false,
        tubo1_8m25R: req.body || false,
        tubo1_8m25L: req.body || false,
        tubo1_8m26R: req.body || false,
        tubo1_8m26L: req.body || false,

        pistonm11R: req.body || false,
        pistonm11L: req.body || false,
        pistonm12R: req.body || false,
        pistonm12L: req.body || false,
        pistonm13R: req.body || false,
        pistonm13L: req.body || false,
        pistonm14R: req.body || false,
        pistonm14L: req.body || false,
        pistonm15R: req.body || false,
        pistonm15L: req.body || false,
        pistonm16R: req.body || false,
        pistonm16L: req.body || false,
        pistonm21R: req.body || false,
        pistonm21L: req.body || false,
        pistonm22R: req.body || false,
        pistonm22L: req.body || false,
        pistonm23R: req.body || false,
        pistonm23L: req.body || false,
        pistonm24R: req.body || false,
        pistonm24L: req.body || false,
        pistonm25R: req.body || false,
        pistonm25L: req.body || false,
        pistonm26R: req.body || false,
        pistonm26L: req.body || false,

        esprea2m11R: req.body || false,
        esprea2m11L: req.body || false,
        esprea2m12R: req.body || false,
        esprea2m12L: req.body || false,
        esprea2m13R: req.body || false,
        esprea2m13L: req.body || false,
        esprea2m14R: req.body || false,
        esprea2m14L: req.body || false,
        esprea2m15R: req.body || false,
        esprea2m15L: req.body || false,
        esprea2m16R: req.body || false,
        esprea2m16L: req.body || false,
        esprea2m21R: req.body || false,
        esprea2m21L: req.body || false,
        esprea2m22R: req.body || false,
        esprea2m22L: req.body || false,
        esprea2m23R: req.body || false,
        esprea2m23L: req.body || false,
        esprea2m24R: req.body || false,
        esprea2m24L: req.body || false,
        esprea2m25R: req.body || false,
        esprea2m25L: req.body || false,
        esprea2m26R: req.body || false,
        esprea2m26L: req.body || false,

        valvula1_3m11R: req.body || false,
        valvula1_3m11L: req.body || false,
        valvula1_3m12R: req.body || false,
        valvula1_3m12L: req.body || false,
        valvula1_3m13R: req.body || false,
        valvula1_3m13L: req.body || false,
        valvula1_3m14R: req.body || false,
        valvula1_3m14L: req.body || false,
        valvula1_3m15R: req.body || false,
        valvula1_3m15L: req.body || false,
        valvula1_3m16R: req.body || false,
        valvula1_3m16L: req.body || false,
        valvula1_3m21R: req.body || false,
        valvula1_3m21L: req.body || false,
        valvula1_3m22R: req.body || false,
        valvula1_3m22L: req.body || false,
        valvula1_3m23R: req.body || false,
        valvula1_3m23L: req.body || false,
        valvula1_3m24R: req.body || false,
        valvula1_3m24L: req.body || false,
        valvula1_3m25R: req.body || false,
        valvula1_3m25L: req.body || false,
        valvula1_3m26R: req.body || false,
        valvula1_3m26L: req.body || false,

        esprea1m11R: req.body || false,
        esprea1m11L: req.body || false,
        esprea1m12R: req.body || false,
        esprea1m12L: req.body || false,
        esprea1m13R: req.body || false,
        esprea1m13L: req.body || false,
        esprea1m14R: req.body || false,
        esprea1m14L: req.body || false,
        esprea1m15R: req.body || false,
        esprea1m15L: req.body || false,
        esprea1m16R: req.body || false,
        esprea1m16L: req.body || false,
        esprea1m21R: req.body || false,
        esprea1m21L: req.body || false,
        esprea1m22R: req.body || false,
        esprea1m22L: req.body || false,
        esprea1m23R: req.body || false,
        esprea1m23L: req.body || false,
        esprea1m24R: req.body || false,
        esprea1m24L: req.body || false,
        esprea1m25R: req.body || false,
        esprea1m25L: req.body || false,
        esprea1m26R: req.body || false,
        esprea1m26L: req.body || false,

        tuercam11R: req.body || false,
        tuercam11L: req.body || false,
        tuercam12R: req.body || false,
        tuercam12L: req.body || false,
        tuercam13R: req.body || false,
        tuercam13L: req.body || false,
        tuercam14R: req.body || false,
        tuercam14L: req.body || false,
        tuercam15R: req.body || false,
        tuercam15L: req.body || false,
        tuercam16R: req.body || false,
        tuercam16L: req.body || false,
        tuercam21R: req.body || false,
        tuercam21L: req.body || false,
        tuercam22R: req.body || false,
        tuercam22L: req.body || false,
        tuercam23R: req.body || false,
        tuercam23L: req.body || false,
        tuercam24R: req.body || false,
        tuercam24L: req.body || false,
        tuercam25R: req.body || false,
        tuercam25L: req.body || false,
        tuercam26R: req.body || false,
        tuercam26L: req.body || false,

        cabezaCm11R: req.body || false,
        cabezaCm11L: req.body || false,
        cabezaCm12R: req.body || false,
        cabezaCm12L: req.body || false,
        cabezaCm13R: req.body || false,
        cabezaCm13L: req.body || false,
        cabezaCm14R: req.body || false,
        cabezaCm14L: req.body || false,
        cabezaCm15R: req.body || false,
        cabezaCm15L: req.body || false,
        cabezaCm16R: req.body || false,
        cabezaCm16L: req.body || false,
        cabezaCm21R: req.body || false,
        cabezaCm21L: req.body || false,
        cabezaCm22R: req.body || false,
        cabezaCm22L: req.body || false,
        cabezaCm23R: req.body || false,
        cabezaCm23L: req.body || false,
        cabezaCm24R: req.body || false,
        cabezaCm24L: req.body || false,
        cabezaCm25R: req.body || false,
        cabezaCm25L: req.body || false,
        cabezaCm26R: req.body || false,
        cabezaCm26L: req.body || false,

        sellom11R: req.body || false,
        sellom11L: req.body || false,
        sellom12R: req.body || false,
        sellom12L: req.body || false,
        sellom13R: req.body || false,
        sellom13L: req.body || false,
        sellom14R: req.body || false,
        sellom14L: req.body || false,
        sellom15R: req.body || false,
        sellom15L: req.body || false,
        sellom16R: req.body || false,
        sellom16L: req.body || false,
        sellom21R: req.body || false,
        sellom21L: req.body || false,
        sellom22R: req.body || false,
        sellom22L: req.body || false,
        sellom23R: req.body || false,
        sellom23L: req.body || false,
        sellom24R: req.body || false,
        sellom24L: req.body || false,
        sellom25R: req.body || false,
        sellom25L: req.body || false,
        sellom26R: req.body || false,
        sellom26L: req.body || false,

        valvula1_1m11R: req.body || false,
        valvula1_1m11L: req.body || false,
        valvula1_1m12R: req.body || false,
        valvula1_1m12L: req.body || false,
        valvula1_1m13R: req.body || false,
        valvula1_1m13L: req.body || false,
        valvula1_1m14R: req.body || false,
        valvula1_1m14L: req.body || false,
        valvula1_1m15R: req.body || false,
        valvula1_1m15L: req.body || false,
        valvula1_1m16R: req.body || false,
        valvula1_1m16L: req.body || false,
        valvula1_1m21R: req.body || false,
        valvula1_1m21L: req.body || false,
        valvula1_1m22R: req.body || false,
        valvula1_1m22L: req.body || false,
        valvula1_1m23R: req.body || false,
        valvula1_1m23L: req.body || false,
        valvula1_1m24R: req.body || false,
        valvula1_1m24L: req.body || false,
        valvula1_1m25R: req.body || false,
        valvula1_1m25L: req.body || false,
        valvula1_1m26R: req.body || false,
        valvula1_1m26L: req.body || false,

        //CILINDROS STCMA/30 -STE TE-06
        tuboCm11R: req.body || false,
        tuboCm11L: req.body || false,
        tuboCm12R: req.body || false,
        tuboCm12L: req.body || false,
        tuboCm13R: req.body || false,
        tuboCm13L: req.body || false,
        tuboCm14R: req.body || false,
        tuboCm14L: req.body || false,
        tuboCm15R: req.body || false,
        tuboCm15L: req.body || false,
        tuboCm16R: req.body || false,
        tuboCm16L: req.body || false,
        tuboCm21R: req.body || false,
        tuboCm21L: req.body || false,
        tuboCm22R: req.body || false,
        tuboCm22L: req.body || false,
        tuboCm23R: req.body || false,
        tuboCm23L: req.body || false,
        tuboCm24R: req.body || false,
        tuboCm24L: req.body || false,
        tuboCm25R: req.body || false,
        tuboCm25L: req.body || false,
        tuboCm26R: req.body || false,
        tuboCm26L: req.body || false,

        cabezaDm11R: req.body || false,
        cabezaDm11L: req.body || false,
        cabezaDm12R: req.body || false,
        cabezaDm12L: req.body || false,
        cabezaDm13R: req.body || false,
        cabezaDm13L: req.body || false,
        cabezaDm14R: req.body || false,
        cabezaDm14L: req.body || false,
        cabezaDm15R: req.body || false,
        cabezaDm15L: req.body || false,
        cabezaDm16R: req.body || false,
        cabezaDm16L: req.body || false,
        cabezaDm21R: req.body || false,
        cabezaDm21L: req.body || false,
        cabezaDm22R: req.body || false,
        cabezaDm22L: req.body || false,
        cabezaDm23R: req.body || false,
        cabezaDm23L: req.body || false,
        cabezaDm24R: req.body || false,
        cabezaDm24L: req.body || false,
        cabezaDm25R: req.body || false,
        cabezaDm25L: req.body || false,
        cabezaDm26R: req.body || false,
        cabezaDm26L: req.body || false,

        ensamblem11R: req.body || false,
        ensamblem11L: req.body || false,
        ensamblem12R: req.body || false,
        ensamblem12L: req.body || false,
        ensamblem13R: req.body || false,
        ensamblem13L: req.body || false,
        ensamblem14R: req.body || false,
        ensamblem14L: req.body || false,
        ensamblem15R: req.body || false,
        ensamblem15L: req.body || false,
        ensamblem16R: req.body || false,
        ensamblem16L: req.body || false,
        ensamblem21R: req.body || false,
        ensamblem21L: req.body || false,
        ensamblem22R: req.body || false,
        ensamblem22L: req.body || false,
        ensamblem23R: req.body || false,
        ensamblem23L: req.body || false,
        ensamblem24R: req.body || false,
        ensamblem24L: req.body || false,
        ensamblem25R: req.body || false,
        ensamblem25L: req.body || false,
        ensamblem26R: req.body || false,
        ensamblem26L: req.body || false,

        vastago06m11R: req.body || false,
        vastago06m11L: req.body || false,
        vastago06m12R: req.body || false,
        vastago06m12L: req.body || false,
        vastago06m13R: req.body || false,
        vastago06m13L: req.body || false,
        vastago06m14R: req.body || false,
        vastago06m14L: req.body || false,
        vastago06m15R: req.body || false,
        vastago06m15L: req.body || false,
        vastago06m16R: req.body || false,
        vastago06m16L: req.body || false,
        vastago06m21R: req.body || false,
        vastago06m21L: req.body || false,
        vastago06m22R: req.body || false,
        vastago06m22L: req.body || false,
        vastago06m23R: req.body || false,
        vastago06m23L: req.body || false,
        vastago06m24R: req.body || false,
        vastago06m24L: req.body || false,
        vastago06m25R: req.body || false,
        vastago06m25L: req.body || false,
        vastago06m26R: req.body || false,
        vastago06m26L: req.body || false,

        camisaAm11R: req.body || false,
        camisaAm11L: req.body || false,
        camisaAm12R: req.body || false,
        camisaAm12L: req.body || false,
        camisaAm13R: req.body || false,
        camisaAm13L: req.body || false,
        camisaAm14R: req.body || false,
        camisaAm14L: req.body || false,
        camisaAm15R: req.body || false,
        camisaAm15L: req.body || false,
        camisaAm16R: req.body || false,
        camisaAm16L: req.body || false,
        camisaAm21R: req.body || false,
        camisaAm21L: req.body || false,
        camisaAm22R: req.body || false,
        camisaAm22L: req.body || false,
        camisaAm23R: req.body || false,
        camisaAm23L: req.body || false,
        camisaAm24R: req.body || false,
        camisaAm24L: req.body || false,
        camisaAm25R: req.body || false,
        camisaAm25L: req.body || false,
        camisaAm26R: req.body || false,
        camisaAm26L: req.body || false,

        cabezaTm12R: req.body || false,
        cabezaTm12L: req.body || false,
        cabezaTm13R: req.body || false,
        cabezaTm13L: req.body || false,
        cabezaTm14R: req.body || false,
        cabezaTm14L: req.body || false,
        cabezaTm15R: req.body || false,
        cabezaTm15L: req.body || false,
        cabezaTm16R: req.body || false,
        cabezaTm16L: req.body || false,
        cabezaTm21R: req.body || false,
        cabezaTm21L: req.body || false,
        cabezaTm22R: req.body || false,
        cabezaTm22L: req.body || false,
        cabezaTm23R: req.body || false,
        cabezaTm23L: req.body || false,
        cabezaTm24R: req.body || false,
        cabezaTm24L: req.body || false,
        cabezaTm25R: req.body || false,
        cabezaTm25L: req.body || false,
        cabezaTm26R: req.body || false,
        cabezaTm26L: req.body || false,

        bandaDm12R: req.body || false,
        bandaDm12L: req.body || false,
        bandaDm13R: req.body || false,
        bandaDm13L: req.body || false,
        bandaDm14R: req.body || false,
        bandaDm14L: req.body || false,
        bandaDm15R: req.body || false,
        bandaDm15L: req.body || false,
        bandaDm16R: req.body || false,
        bandaDm16L: req.body || false,
        bandaDm21R: req.body || false,
        bandaDm21L: req.body || false,
        bandaDm22R: req.body || false,
        bandaDm22L: req.body || false,
        bandaDm23R: req.body || false,
        bandaDm23L: req.body || false,
        bandaDm24R: req.body || false,
        bandaDm24L: req.body || false,
        bandaDm25R: req.body || false,
        bandaDm25L: req.body || false,
        bandaDm26R: req.body || false,
        bandaDm26L: req.body || false,

        oringsm12R: req.body || false,
        oringsm12L: req.body || false,
        oringsm13R: req.body || false,
        oringsm13L: req.body || false,
        oringsm14R: req.body || false,
        oringsm14L: req.body || false,
        oringsm15R: req.body || false,
        oringsm15L: req.body || false,
        oringsm16R: req.body || false,
        oringsm16L: req.body || false,
        oringsm21R: req.body || false,
        oringsm21L: req.body || false,
        oringsm22R: req.body || false,
        oringsm22L: req.body || false,
        oringsm23R: req.body || false,
        oringsm23L: req.body || false,
        oringsm24R: req.body || false,
        oringsm24L: req.body || false,
        oringsm25R: req.body || false,
        oringsm25L: req.body || false,
        oringsm26R: req.body || false,
        oringsm26L: req.body || false,

        valvulaC1_1m12R: req.body || false,
        valvulaC1_1m12L: req.body || false,
        valvulaC1_1m13R: req.body || false,
        valvulaC1_1m13L: req.body || false,
        valvulaC1_1m14R: req.body || false,
        valvulaC1_1m14L: req.body || false,
        valvulaC1_1m15R: req.body || false,
        valvulaC1_1m15L: req.body || false,
        valvulaC1_1m16R: req.body || false,
        valvulaC1_1m16L: req.body || false,
        valvulaC1_1m21R: req.body || false,
        valvulaC1_1m21L: req.body || false,
        valvulaC1_1m22R: req.body || false,
        valvulaC1_1m22L: req.body || false,
        valvulaC1_1m23R: req.body || false,
        valvulaC1_1m23L: req.body || false,
        valvulaC1_1m24R: req.body || false,
        valvulaC1_1m24L: req.body || false,
        valvulaC1_1m25R: req.body || false,
        valvulaC1_1m25L: req.body || false,
        valvulaC1_1m26R: req.body || false,
        valvulaC1_1m26L: req.body || false,

        valvulaC0_8m12R: req.body || false,
        valvulaC0_8m12L: req.body || false,
        valvulaC0_8m13R: req.body || false,
        valvulaC0_8m13L: req.body || false,
        valvulaC0_8m14R: req.body || false,
        valvulaC0_8m14L: req.body || false,
        valvulaC0_8m15R: req.body || false,
        valvulaC0_8m15L: req.body || false,
        valvulaC0_8m16R: req.body || false,
        valvulaC0_8m16L: req.body || false,
        valvulaC0_8m21R: req.body || false,
        valvulaC0_8m21L: req.body || false,
        valvulaC0_8m22R: req.body || false,
        valvulaC0_8m22L: req.body || false,
        valvulaC0_8m23R: req.body || false,
        valvulaC0_8m23L: req.body || false,
        valvulaC0_8m24R: req.body || false,
        valvulaC0_8m24L: req.body || false,
        valvulaC0_8m25R: req.body || false,
        valvulaC0_8m25L: req.body || false,
        valvulaC0_8m26R: req.body || false,
        valvulaC0_8m26L: req.body || false,

        ensamble06m12R: req.body || false,
        ensamble06m12L: req.body || false,
        ensamble06m13R: req.body || false,
        ensamble06m13L: req.body || false,
        ensamble06m14R: req.body || false,
        ensamble06m14L: req.body || false,
        ensamble06m15R: req.body || false,
        ensamble06m15L: req.body || false,
        ensamble06m16R: req.body || false,
        ensamble06m16L: req.body || false,
        ensamble06m21R: req.body || false,
        ensamble06m21L: req.body || false,
        ensamble06m22R: req.body || false,
        ensamble06m22L: req.body || false,
        ensamble06m23R: req.body || false,
        ensamble06m23L: req.body || false,
        ensamble06m24R: req.body || false,
        ensamble06m24L: req.body || false,
        ensamble06m25R: req.body || false,
        ensamble06m25L: req.body || false,
        ensamble06m26R: req.body || false,
        ensamble06m26L: req.body || false,

        observaciones: req.body.obs,

        materialUtilizado: materiales,
    };
    await mmmeC19.findByIdAndUpdate(id, { $set: MMME_C19}, { new: true });
    res.json({
        status: 'Employee update'
    });
}
MMME_C19.checkedApprovalByWorker = async (req, res) => {
    const { id } = req.params;
    const checked = {
        documentFormCurrentState: req.body
    }
    await mmmeC19.findByIdAndUpdate(id, { $set: checked }, { new: true });
    res.json({
        status: 'worker state update'
    })
}
MMME_C19.getStateCheckedApprovalByWorker = async (req, res) => {
    const { id } = req.params;
    const state = await mmmeC19.findById(id, {
        "_id": 1, 
        "documentFormCurrentState": 1
    })
    res.json(state)
}
MMME_C19.getAllMaintenenceMMME_C19 = async (req, res) => {
    const maintenances = await mmmeC19.find({}, {
        "_id": 1, 
        "unidad": 1, 
        "documentFormCurrentState.approvalByWorker.checked": 1, 
        "documentFormCurrentState.approvalBySupervisor.checked": 1,
        "documentFormCurrentState.approvalByMannager.checked": 1,
        "documentFormCurrentState.loading": 1
    })
    res.json(maintenances)
}
MMME_C19.addNewHistoryrecord = async (req, res) => {
    const { id } = req.params;
    const historyMMME_C19New = {
        historyFile: req.body.historyFile || []
    }
    await mmmeC19.findByIdAndUpdate(id, { $set: historyMMME_C19New }, { new: true });
    res.json({
        status: 'History update'
    })
}
MMME_C19.getHistoryOF = async (req, res) => {
    const { id } = req.params;
    const maintenances = await mmmeC19.findById(id, {
        "_id": 0, 
        "historyFile": 1
    })
    res.json(maintenances)
}
MMME_C19.createMaintenenceMMME_C19 = async (req, res) => {
    const maintenence = new mmmeC19(req.body)
    await maintenence.save()
    res.json({res: 'Ok'})
};
module.exports = MMME_C19;