'use strict'//usar novedades de JS

var mongoose = require('mongoose');//modulo de moongose
var Schema = mongoose.Schema;//Schema carga moongoose.Schema esto permite definir nuevos esquemas

var mmmeB02Schema = Schema({//esquema de la estructura que va a tener el formulario
    date_created: { type: Date, required: true },
    //datos tren
    noInspeccion: { type: String },
    noTren: { type: String },
    kilometraje: { type: String },
    horaInicio: { type: String },
    horaTerminacion: { type: String },
    
    operario: { type: String, required: true},
    id_worker: {type: String},
    unidad: { type: Number, required: true },

    nivelAM1e1R: Boolean,
    nivelAM1e1A: Boolean,
    nivelAM1e2R: Boolean,
    nivelAM1e2A: Boolean,
    nivelAM2e1R: Boolean,
    nivelAM2e1A: Boolean,
    nivelAM2e2R: Boolean,
    nivelAM2e2A: Boolean,

    taponesMM1e1L: Boolean,
    taponesMM1e1R: Boolean,
    taponesMM1e1A: Boolean,
    taponesMM1e2L: Boolean,
    taponesMM1e2R: Boolean,
    taponesMM1e2A: Boolean,
    taponesMM2e1L: Boolean,
    taponesMM2e1R: Boolean,
    taponesMM2e1A: Boolean,
    taponesMM2e2L: Boolean,
    taponesMM2e2R: Boolean,
    taponesMM2e2A: Boolean,

    tornillosAM1e1L: Boolean,
    tornillosAM1e1R: Boolean,
    tornillosAM1e1A: Boolean,
    tornillosAM1e2L: Boolean,
    tornillosAM1e2R: Boolean,
    tornillosAM1e2A: Boolean,
    tornillosAM2e1L: Boolean,
    tornillosAM2e1R: Boolean,
    tornillosAM2e1A: Boolean,
    tornillosAM2e2L: Boolean,
    tornillosAM2e2R: Boolean,
    tornillosAM2e2A: Boolean,

    respiraderosM1e1L: Boolean,
    respiraderosM1e1R: Boolean,
    respiraderosM1e1A: Boolean,
    respiraderosM1e2L: Boolean,
    respiraderosM1e2R: Boolean,
    respiraderosM1e2A: Boolean,
    respiraderosM2e1L: Boolean,
    respiraderosM2e1R: Boolean,
    respiraderosM2e1A: Boolean,
    respiraderosM2e2L: Boolean,
    respiraderosM2e2R: Boolean,
    respiraderosM2e2A: Boolean,

    cajaEM1e1L: Boolean,
    cajaEM1e1R: Boolean,
    cajaEM1e2L: Boolean,
    cajaEM1e2R: Boolean,
    cajaEM2e1L: Boolean,
    cajaEM2e1R: Boolean,
    cajaEM2e2L: Boolean,
    cajaEM2e2R: Boolean,
    
    cilindrosFM1e1L: Boolean,
    cilindrosFM1e1R: Boolean,
    cilindrosFM1e1A: Boolean,
    cilindrosFM1e2L: Boolean,
    cilindrosFM1e2R: Boolean,
    cilindrosFM1e2A: Boolean,
    cilindrosFRe1L: Boolean,
    cilindrosFRe1R: Boolean,
    cilindrosFRe1A: Boolean,
    cilindrosFRe2L: Boolean,
    cilindrosFRe2R: Boolean,
    cilindrosFRe2A: Boolean,
    cilindrosFM2e1L: Boolean,
    cilindrosFM2e1R: Boolean,
    cilindrosFM2e1A: Boolean,
    cilindrosFM2e2L: Boolean,
    cilindrosFM2e2R: Boolean,
    cilindrosFM2e2A: Boolean,

    chicoteDRe1L: Boolean,
    chicoteDRe1R: Boolean,
    chicoteDRe1A: Boolean,
    chicoteDRe2L: Boolean,
    chicoteDRe2R: Boolean,
    chicoteDRe2A: Boolean,
    
    mangueraAM1e1L: Boolean,
    mangueraAM1e1R: Boolean,
    mangueraAM1e1A: Boolean,
    mangueraAM1e2L: Boolean,
    mangueraAM1e2R: Boolean,
    mangueraAM1e2A: Boolean,
    mangueraARe1L: Boolean,
    mangueraARe1R: Boolean,
    mangueraARe1A: Boolean,
    mangueraARe2L: Boolean,
    mangueraARe2R: Boolean,
    mangueraARe2A: Boolean,
    mangueraAM2e1L: Boolean,
    mangueraAM2e1R: Boolean,
    mangueraAM2e1A: Boolean,
    mangueraAM2e2L: Boolean,
    mangueraAM2e2R: Boolean,
    mangueraAM2e2A: Boolean,

    cableadoFrostM1e1L: Boolean,
    cableadoFrostM1e1R: Boolean,
    cableadoFrostM1e1A: Boolean,
    cableadoFrostM1e2L: Boolean,
    cableadoFrostM1e2R: Boolean,
    cableadoFrostM1e2A: Boolean,
    cableadoFrostRe1L: Boolean,
    cableadoFrostRe1R: Boolean,
    cableadoFrostRe1A: Boolean,
    cableadoFrostRe2L: Boolean,
    cableadoFrostRe2R: Boolean,
    cableadoFrostRe2A: Boolean,
    cableadoFrostM2e1L: Boolean,
    cableadoFrostM2e1R: Boolean,
    cableadoFrostM2e1A: Boolean,
    cableadoFrostM2e2L: Boolean,
    cableadoFrostM2e2R: Boolean,
    cableadoFrostM2e2A: Boolean,

    seguroLM1e1L: Boolean,
    seguroLM1e1R: Boolean,
    seguroLM1e1A: Boolean,
    seguroLM1e2L: Boolean,
    seguroLM1e2R: Boolean,
    seguroLM1e2A: Boolean,
    seguroLRe1L: Boolean,
    seguroLRe1R: Boolean,
    seguroLRe1A: Boolean,
    seguroLRe2L: Boolean,
    seguroLRe2R: Boolean,
    seguroLRe2A: Boolean,
    seguroLM2e1L: Boolean,
    seguroLM2e1R: Boolean,
    seguroLM2e1A: Boolean,
    seguroLM2e2L: Boolean,
    seguroLM2e2R: Boolean,
    seguroLM2e2A: Boolean,

    mangueraSM1e1L: Boolean,
    mangueraSM1e1R: Boolean,
    mangueraSM1e1A: Boolean,
    mangueraSM1e2L: Boolean,
    mangueraSM1e2R: Boolean,
    mangueraSM1e2A: Boolean,
    mangueraSRe1L: Boolean,
    mangueraSRe1R: Boolean,
    mangueraSRe1A: Boolean,
    mangueraSRe2L: Boolean,
    mangueraSRe2R: Boolean,
    mangueraSRe2A: Boolean,
    mangueraSM2e1L: Boolean,
    mangueraSM2e1R: Boolean,
    mangueraSM2e1A: Boolean,
    mangueraSM2e2L: Boolean,
    mangueraSM2e2R: Boolean,
    mangueraSM2e2A: Boolean,

    mangueraIM1e1L: Boolean,
    mangueraIM1e1R: Boolean,
    mangueraIM1e1A: Boolean,
    mangueraIM1e2L: Boolean,
    mangueraIM1e2R: Boolean,
    mangueraIM1e2A: Boolean,
    mangueraIRe1L: Boolean,
    mangueraIRe1R: Boolean,
    mangueraIRe1A: Boolean,
    mangueraIRe2L: Boolean,
    mangueraIRe2R: Boolean,
    mangueraIRe2A: Boolean,
    mangueraIM2e1L: Boolean,
    mangueraIM2e1R: Boolean,
    mangueraIM2e1A: Boolean,
    mangueraIM2e2L: Boolean,
    mangueraIM2e2R: Boolean,
    mangueraIM2e2A: Boolean,

    amortiguadorDM1e1L: Boolean,
    amortiguadorDM1e1R: Boolean,
    amortiguadorDM1e1A: Boolean,
    amortiguadorDM1e2L: Boolean,
    amortiguadorDM1e2R: Boolean,
    amortiguadorDM1e2A: Boolean,
    amortiguadorDRe1L: Boolean,
    amortiguadorDRe1R: Boolean,
    amortiguadorDRe1A: Boolean,
    amortiguadorDRe2L: Boolean,
    amortiguadorDRe2R: Boolean,
    amortiguadorDRe2A: Boolean,
    amortiguadorDM2e1L: Boolean,
    amortiguadorDM2e1R: Boolean,
    amortiguadorDM2e1A: Boolean,
    amortiguadorDM2e2L: Boolean,
    amortiguadorDM2e2R: Boolean,
    amortiguadorDM2e2A: Boolean,

    amortiguadorIM1e1L: Boolean,
    amortiguadorIM1e1R: Boolean,
    amortiguadorIM1e1A: Boolean,
    amortiguadorIM1e2L: Boolean,
    amortiguadorIM1e2R: Boolean,
    amortiguadorIM1e2A: Boolean,
    amortiguadorIRe1L: Boolean,
    amortiguadorIRe1R: Boolean,
    amortiguadorIRe1A: Boolean,
    amortiguadorIRe2L: Boolean,
    amortiguadorIRe2R: Boolean,
    amortiguadorIRe2A: Boolean,
    amortiguadorIM2e1L: Boolean,
    amortiguadorIM2e1R: Boolean,
    amortiguadorIM2e1A: Boolean,
    amortiguadorIM2e2L: Boolean,
    amortiguadorIM2e2R: Boolean,
    amortiguadorIM2e2A: Boolean,

    amortiguadorVM1e1L: Boolean,
    amortiguadorVM1e1R: Boolean,
    amortiguadorVM1e1A: Boolean,
    amortiguadorVM1e2L: Boolean,
    amortiguadorVM1e2R: Boolean,
    amortiguadorVM1e2A: Boolean,
    amortiguadorVRe1L: Boolean,
    amortiguadorVRe1R: Boolean,
    amortiguadorVRe1A: Boolean,
    amortiguadorVRe2L: Boolean,
    amortiguadorVRe2R: Boolean,
    amortiguadorVRe2A: Boolean,
    amortiguadorVM2e1L: Boolean,
    amortiguadorVM2e1R: Boolean,
    amortiguadorVM2e1A: Boolean,
    amortiguadorVM2e2L: Boolean,
    amortiguadorVM2e2R: Boolean,
    amortiguadorVM2e2A: Boolean,

    trenzasCRe1L: Boolean,
    trenzasCRe1R: Boolean,
    trenzasCRe1A: Boolean,
    trenzasCRe2L: Boolean,
    trenzasCRe2R: Boolean,
    trenzasCRe2A: Boolean,
    
    trenzasDM1e1R: Boolean,
    trenzasDM1e2R: Boolean,
    trenzasDRe1R: Boolean,
    trenzasDRe2R: Boolean,
    trenzasDM2e1R: Boolean,
    trenzasDM2e2R: Boolean,
    
    trenzasIM1e1R: Boolean,
    trenzasIM1e2R: Boolean,
    trenzasIRe1R: Boolean,
    trenzasIRe2R: Boolean,
    trenzasIM2e1R: Boolean,
    trenzasIM2e2R: Boolean,
    
    valvulaSM1e1L: Boolean,
    valvulaSM1e1R: Boolean,
    valvulaSM1e1A: Boolean,
    valvulaSRe1L: Boolean,
    valvulaSRe1R: Boolean,
    valvulaSRe1A: Boolean,
    valvulaSM2e1L: Boolean,
    valvulaSM2e1R: Boolean,
    valvulaSM2e1A: Boolean,
    
    valvulaSsM1e1L: Boolean,
    valvulaSsM1e1R: Boolean,
    valvulaSsM1e1A: Boolean,
    valvulaSsM1e2L: Boolean,
    valvulaSsM1e2R: Boolean,
    valvulaSsM1e2A: Boolean,
    valvulaSsRe1L: Boolean,
    valvulaSsRe1R: Boolean,
    valvulaSsRe1A: Boolean,
    valvulaSsM2e1L: Boolean,
    valvulaSsM2e1R: Boolean,
    valvulaSsM2e1A: Boolean,
    valvulaSsM2e2L: Boolean,
    valvulaSsM2e2R: Boolean,
    valvulaSsM2e2A: Boolean,

    tomasRM1e1L: Boolean,
    tomasRM1e1R: Boolean,
    tomasRM1e1A: Boolean,
    tomasRM1e2L: Boolean,
    tomasRM1e2R: Boolean,
    tomasRM1e2A: Boolean,
    tomasRRe1L: Boolean,
    tomasRRe1R: Boolean,
    tomasRRe1A: Boolean,
    tomasRM2e1L: Boolean,
    tomasRM2e1R: Boolean,
    tomasRM2e1A: Boolean,
    tomasRM2e2L: Boolean,
    tomasRM2e2R: Boolean,
    tomasRM2e2A: Boolean,

    amortiguadorHM1e1L: Boolean,
    amortiguadorHM1e1R: Boolean,
    amortiguadorHM1e1A: Boolean,
    amortiguadorHRe1L: Boolean,
    amortiguadorHRe1R: Boolean,
    amortiguadorHRe1A: Boolean,
    amortiguadorHM2e1L: Boolean,
    amortiguadorHM2e1R: Boolean,
    amortiguadorHM2e1A: Boolean,
    
    mangueraBbM1e1L: Boolean,
    mangueraBbM1e1R: Boolean,
    mangueraBbM1e1A: Boolean,
    mangueraBbM2e1L: Boolean,
    mangueraBbM2e1R: Boolean,
    mangueraBbM2e1A: Boolean,

    mangueraBvRe1L: Boolean,
    mangueraBvRe1R: Boolean,
    mangueraBvRe1A: Boolean,
    mangueraBvRe2L: Boolean,
    mangueraBvRe2R: Boolean,
    mangueraBvRe2A: Boolean,

    mangueraFM1e1L: Boolean,
    mangueraFM1e1R: Boolean,
    mangueraFM1e1A: Boolean,
    mangueraFM1e2L: Boolean,
    mangueraFM1e2R: Boolean,
    mangueraFM1e2A: Boolean,
    mangueraFRe1L: Boolean,
    mangueraFRe1R: Boolean,
    mangueraFRe1A: Boolean,
    mangueraFRe2L: Boolean,
    mangueraFRe2R: Boolean,
    mangueraFRe2A: Boolean,
    mangueraFM2e1L: Boolean,
    mangueraFM2e1R: Boolean,
    mangueraFM2e1A: Boolean,
    mangueraFM2e2L: Boolean,
    mangueraFM2e2R: Boolean,
    mangueraFM2e2A: Boolean,

    trenzasBbM1e1L: Boolean,
    trenzasBbM1e1R: Boolean,
    trenzasBbM1e1A: Boolean,
    trenzasBbM1e2L: Boolean,
    trenzasBbM1e2R: Boolean,
    trenzasBbM1e2A: Boolean,
    trenzasBbRe1L: Boolean,
    trenzasBbRe1R: Boolean,
    trenzasBbRe1A: Boolean,
    trenzasBbRe2L: Boolean,
    trenzasBbRe2R: Boolean,
    trenzasBbRe2A: Boolean,
    trenzasBbM2e1L: Boolean,
    trenzasBbM2e1R: Boolean,
    trenzasBbM2e1A: Boolean,
    trenzasBbM2e2L: Boolean,
    trenzasBbM2e2R: Boolean,
    trenzasBbM2e2A: Boolean,

    trenzasBmM1e1L: Boolean,
    trenzasBmM1e1R: Boolean,
    trenzasBmM1e1A: Boolean,
    trenzasBmM1e2L: Boolean,
    trenzasBmM1e2R: Boolean,
    trenzasBmM1e2A: Boolean,
    trenzasBmM2e1L: Boolean,
    trenzasBmM2e1R: Boolean,
    trenzasBmM2e1A: Boolean,
    trenzasBmM2e2L: Boolean,
    trenzasBmM2e2R: Boolean,
    trenzasBmM2e2A: Boolean,

    tuberiaSM1e1L: Boolean,
    tuberiaSM1e1R: Boolean,
    tuberiaSM1e1A: Boolean,
    tuberiaSM1e2L: Boolean,
    tuberiaSM1e2R: Boolean,
    tuberiaSM1e2A: Boolean,
    tuberiaSRe1L: Boolean,
    tuberiaSRe1R: Boolean,
    tuberiaSRe1A: Boolean,
    tuberiaSRe2L: Boolean,
    tuberiaSRe2R: Boolean,
    tuberiaSRe2A: Boolean,
    tuberiaSM2e1L: Boolean,
    tuberiaSM2e1R: Boolean,
    tuberiaSM2e1A: Boolean,
    tuberiaSM2e2L: Boolean,
    tuberiaSM2e2R: Boolean,
    tuberiaSM2e2A: Boolean,

    tuberiaFM1e1L: Boolean,
    tuberiaFM1e1R: Boolean,
    tuberiaFM1e1A: Boolean,
    tuberiaFM1e2L: Boolean,
    tuberiaFM1e2R: Boolean,
    tuberiaFM1e2A: Boolean,
    tuberiaFRe1L: Boolean,
    tuberiaFRe1R: Boolean,
    tuberiaFRe1A: Boolean,
    tuberiaFRe2L: Boolean,
    tuberiaFRe2R: Boolean,
    tuberiaFRe2A: Boolean,
    tuberiaFM2e1L: Boolean,
    tuberiaFM2e1R: Boolean,
    tuberiaFM2e1A: Boolean,
    tuberiaFM2e2L: Boolean,
    tuberiaFM2e2R: Boolean,
    tuberiaFM2e2A: Boolean,

    cableadoMM1e1L: Boolean,
    cableadoMM1e1R: Boolean,
    cableadoMM1e1A: Boolean,
    cableadoMM1e2L: Boolean,
    cableadoMM1e2R: Boolean,
    cableadoMM1e2A: Boolean,
    cableadoMM2e1L: Boolean,
    cableadoMM2e1R: Boolean,
    cableadoMM2e1A: Boolean,
    cableadoMM2e2L: Boolean,
    cableadoMM2e2R: Boolean,
    cableadoMM2e2A: Boolean,

    busquedaFM1: Boolean,
    busquedaFR: Boolean,
    busquedaFM2: Boolean,
        
    observaciones1: String,

    //PARTE2
    frenosEm1LdL: Boolean,
    frenosEm1LdR: Boolean,
    frenosEm1LdA: Boolean,
    frenosEm1LiL: Boolean,
    frenosEm1LiR: Boolean,
    frenosEm1LiA: Boolean,
    frenosErLdL: Boolean,
    frenosErLdR: Boolean,
    frenosErLdA: Boolean,
    frenosErLiL: Boolean,
    frenosErLiR: Boolean,
    frenosErLiA: Boolean,
    frenosEm2LdL: Boolean,
    frenosEm2LdR: Boolean,
    frenosEm2LdA: Boolean,
    frenosEm2LiL: Boolean,
    frenosEm2LiR: Boolean,
    frenosEm2LiA: Boolean,

    cableadoFm1LdL: Boolean,
    cableadoFm1LdR: Boolean,
    cableadoFm1LdA: Boolean,
    cableadoFm1LiL: Boolean,
    cableadoFm1LiR: Boolean,
    cableadoFm1LiA: Boolean,
    cableadoFrLdL: Boolean,
    cableadoFrLdR: Boolean,
    cableadoFrLdA: Boolean,
    cableadoFrLiL: Boolean,
    cableadoFrLiR: Boolean,
    cableadoFrLiA: Boolean,
    cableadoFm2LdL: Boolean,
    cableadoFm2LdR: Boolean,
    cableadoFm2LdA: Boolean,
    cableadoFm2LiL: Boolean,
    cableadoFm2LiR: Boolean,
    cableadoFm2LiA: Boolean,

    trenzasFm1LdL: Boolean,
    trenzasFm1LdR: Boolean,
    trenzasFm1LdA: Boolean,
    trenzasFm1LiL: Boolean,
    trenzasFm1LiR: Boolean,
    trenzasFm1LiA: Boolean,
    trenzasFrLdL: Boolean,
    trenzasFrLdR: Boolean,
    trenzasFrLdA: Boolean,
    trenzasFrLiL: Boolean,
    trenzasFrLiR: Boolean,
    trenzasFrLiA: Boolean,
    trenzasFm2LdL: Boolean,
    trenzasFm2LdR: Boolean,
    trenzasFm2LdA: Boolean,
    trenzasFm2LiL: Boolean,
    trenzasFm2LiR: Boolean,
    trenzasFm2LiA: Boolean,

    //REVISION DE TORQUES Y ELEMENTOS DE FIJACION
    tornilloCm1e1: Boolean,
    tornilloCm1e2: Boolean,
    tornilloCm2e1: Boolean,
    tornilloCm2e2: Boolean,
    observacionesTc: String,

    respiraderosm1e1: Boolean,
    respiraderosm1e2: Boolean,
    respiraderosm2e1: Boolean,
    respiraderosm2e2: Boolean,
    observacionesR: String,

    //REVISION DE LAS BALATAS EN MILIMETROS
    pastaSupIntM1Ld: Boolean,
    pastaSupIntM1Li: Boolean,
    pastaSupIntRLd: Boolean,
    pastaSupIntRLi: Boolean,
    pastaSupIntM2Ld: Boolean,
    pastaSupIntM2Li: Boolean,

    pastaInfIntM1Ld: Boolean,
    pastaInfIntM1Li: Boolean,
    pastaInfIntRLd: Boolean,
    pastaInfIntRLi: Boolean,
    pastaInfIntM2Ld: Boolean,
    pastaInfIntM2Li: Boolean,

    pastaSupExtM1Ld: Boolean,
    pastaSupExtM1Li: Boolean,
    pastaSupExtRLd: Boolean,
    pastaSupExtRLi: Boolean,
    pastaSupExtM2Ld: Boolean,
    pastaSupExtM2Li: Boolean,

    pastaInfExtM1Ld: Boolean,
    pastaInfExtM1Li: Boolean,
    pastaInfExtRLd: Boolean,
    pastaInfExtRLi: Boolean,
    pastaInfExtM2Ld: Boolean,
    pastaInfExtM2Li: Boolean,

    observaciones2: String,

    //material utilizado
    materialUtilizado: {
        numberOfMaterial: Number,    
        arr: [{
            _id: String,
            code: String,
            description: String,
            voucherNumber: String,
            quantity: String,
        }]
    },

    documentFormCurrentState: {
        approvalByWorker    : { id_worker: String, checked: Boolean },
        approvalBySupervisor: { id_worker: String, checked: Boolean },
        approvalByMannager  : { id_worker: String, checked: Boolean },
        loading: Boolean
    },

    historyFile: [
        {
            id_worker: String,
            workerName: String,
            editDate: Date,
            editValue: Number
        }
    ]
});
module.exports = mongoose.model('mmmeB02', mmmeB02Schema);