'use strict'//usar novedades de JS

var mongoose = require('mongoose');//modulo de moongose
var Schema = mongoose.Schema;//Schema carga moongoose.Schema esto permite definir nuevos esquemas

var mmmeC16Schema = Schema({//esquema de la estructura que va a tener el formulario
    date_created: { type: Date, required: true },
    //datos tren
    noInspeccion: { type: String },
    noTren: { type: String },
    kilometraje: { type: String },
    horaInicio: { type: String },
    horaTerminacion: { type: String },
    
    operario: { type: String, required: true},
    id_worker: {type: String},
    unidad: { type: Number, required: true },

    bulonM1Rev: Boolean,
    bulonM1Limp: Boolean, 
    bulonM1Camb: Boolean,
    bulonM2Rev: Boolean,
    bulonM2Limp: Boolean, 
    bulonM2Camb: Boolean,
    observacionesB: String,

    prisioneroM1Rev: Boolean,
    prisioneroM1Limp: Boolean,
    prisioneroM1Lub: Boolean, 
    prisioneroM1Camb: Boolean,
    prisioneroM2Rev: Boolean,
    prisioneroM2Limp: Boolean, 
    prisioneroM2Lub: Boolean, 
    prisioneroM2Camb: Boolean,
    observacionesP: String,

    tapaPM1Rev: Boolean,
    tapaPM1Limp: Boolean,
    tapaPM1Lub: Boolean, 
    tapaPM1Camb: Boolean,
    tapaPM2Rev: Boolean,
    tapaPM2Limp: Boolean, 
    tapaPM2Lub: Boolean, 
    tapaPM2Camb: Boolean,
    observacionesTp: String,

    tornilloM1Rev: Boolean,
    tornilloM1Limp: Boolean,
    tornilloM1Lub: Boolean, 
    tornilloM1Camb: Boolean,
    tornilloM2Rev: Boolean,
    tornilloM2Limp: Boolean, 
    tornilloM2Lub: Boolean, 
    tornilloM2Camb: Boolean,
    observacionesT: String,

    sirgaM1Rev: Boolean,
    sirgaM1Limp: Boolean,
    sirgaM1Lub: Boolean, 
    sirgaM1Camb: Boolean,
    sirgaM2Rev: Boolean,
    sirgaM2Limp: Boolean, 
    sirgaM2Lub: Boolean, 
    sirgaM2Camb: Boolean,
    observacionesS: String,

    anilloSM1Rev: Boolean,
    anilloSM1Limp: Boolean,
    anilloSM1Lub: Boolean, 
    anilloSM1Camb: Boolean,
    anilloSM2Rev: Boolean,
    anilloSM2Limp: Boolean, 
    anilloSM2Lub: Boolean, 
    anilloSM2Camb: Boolean,
    observacionesAs: String,

    cuerpoM1Rev: Boolean,
    cuerpoM1Limp: Boolean,
    cuerpoM1Lub: Boolean, 
    cuerpoM1Camb: Boolean,
    cuerpoM2Rev: Boolean,
    cuerpoM2Limp: Boolean, 
    cuerpoM2Lub: Boolean, 
    cuerpoM2Camb: Boolean,
    observacionesC: String,

    juntaOM1Rev: Boolean,
    juntaOM1Limp: Boolean,
    juntaOM1Lub: Boolean, 
    juntaOM1Camb: Boolean,
    juntaOM2Rev: Boolean,
    juntaOM2Limp: Boolean, 
    juntaOM2Lub: Boolean, 
    juntaOM2Camb: Boolean,
    observacionesJo: String,

    bridaIM1Rev: Boolean,
    bridaIM1Limp: Boolean,
    bridaIM1Lub: Boolean, 
    bridaIM1Camb: Boolean,
    bridaIM2Rev: Boolean,
    bridaIM2Limp: Boolean, 
    bridaIM2Lub: Boolean, 
    bridaIM2Camb: Boolean,
    observacionesBi: String,

    tapasM1Rev: Boolean,
    tapasM1Limp: Boolean,
    tapasM1Lub: Boolean, 
    tapasM1Camb: Boolean,
    tapasM2Rev: Boolean,
    tapasM2Limp: Boolean, 
    tapasM2Lub: Boolean, 
    tapasM2Camb: Boolean,
    observacionesTapas: String,

    husilloM1Rev: Boolean,
    husilloM1Limp: Boolean,
    husilloM1Lub: Boolean, 
    husilloM1Camb: Boolean,
    husilloM2Rev: Boolean,
    husilloM2Limp: Boolean, 
    husilloM2Lub: Boolean, 
    husilloM2Camb: Boolean,
    observacionesH: String,

    tuercaM1Rev: Boolean,
    tuercaM1Limp: Boolean,
    tuercaM1Lub: Boolean, 
    tuercaM1Camb: Boolean,
    tuercaM2Rev: Boolean,
    tuercaM2Limp: Boolean, 
    tuercaM2Lub: Boolean, 
    tuercaM2Camb: Boolean,
    observacionesTuerca: String,

    pasadorEM1Rev: Boolean,
    pasadorEM1Limp: Boolean,
    pasadorEM1Lub: Boolean, 
    pasadorEM1Camb: Boolean,
    pasadorEM2Rev: Boolean,
    pasadorEM2Limp: Boolean, 
    pasadorEM2Lub: Boolean, 
    pasadorEM2Camb: Boolean,
    observacionesPe: String,

    cojineteRM1Rev: Boolean,
    cojineteRM1Limp: Boolean,
    cojineteRM1Lub: Boolean, 
    cojineteRM1Camb: Boolean,
    cojineteRM2Rev: Boolean,
    cojineteRM2Limp: Boolean, 
    cojineteRM2Lub: Boolean, 
    cojineteRM2Camb: Boolean,
    observacionesCr: String,

    tornillosCM1Rev: Boolean,
    tornillosCM1Limp: Boolean,
    tornillosCM1Lub: Boolean, 
    tornillosCM1Camb: Boolean,
    tornillosCM2Rev: Boolean,
    tornillosCM2Limp: Boolean, 
    tornillosCM2Lub: Boolean, 
    tornillosCM2Camb: Boolean,
    observacionesTc: String,

    arandelaEM1Rev: Boolean,
    arandelaEM1Limp: Boolean,
    arandelaEM1Lub: Boolean, 
    arandelaEM1Camb: Boolean,
    arandelaEM2Rev: Boolean,
    arandelaEM2Limp: Boolean, 
    arandelaEM2Lub: Boolean, 
    arandelaEM2Camb: Boolean,
    observacionesAe: String,

    dicoM1Rev: Boolean,
    dicoM1Limp: Boolean,
    dicoM1Lub: Boolean, 
    dicoM1Camb: Boolean,
    dicoM2Rev: Boolean,
    dicoM2Limp: Boolean, 
    dicoM2Lub: Boolean, 
    dicoM2Camb: Boolean,
    observacionesD: String,

    muelleM1Rev: Boolean,
    muelleM1Limp: Boolean,
    muelleM1Lub: Boolean, 
    muelleM1Camb: Boolean,
    muelleM2Rev: Boolean,
    muelleM2Limp: Boolean, 
    muelleM2Lub: Boolean, 
    muelleM2Camb: Boolean,
    observacionesM: String,

    tornilloRM1Rev: Boolean,
    tornilloRM1Limp: Boolean,
    tornilloRM1Lub: Boolean, 
    tornilloRM1Camb: Boolean,
    tornilloRM2Rev: Boolean,
    tornilloRM2Limp: Boolean, 
    tornilloRM2Lub: Boolean, 
    tornilloRM2Camb: Boolean,
    observacionesTr: String,

    chicoteM1Rev: Boolean,
    chicoteM1Limp: Boolean,
    chicoteM1Camb: Boolean,
    chicoteM2Rev: Boolean,
    chicoteM2Limp: Boolean, 
    chicoteM2Camb: Boolean,
    observacionesCh: String,
    
    //material utilizado
    materialUtilizado: {
        numberOfMaterial: Number,    
        arr: [{
            _id: String,
            code: String,
            description: String,
            voucherNumber: String,
            quantity: String,
        }]
    },

    documentFormCurrentState: {
        approvalByWorker    : { id_worker: String, checked: Boolean },
        approvalBySupervisor: { id_worker: String, checked: Boolean },
        approvalByMannager  : { id_worker: String, checked: Boolean },
        loading: Boolean
    },

    historyFile: [
        {
            id_worker: String,
            workerName: String,
            editDate: Date,
            editValue: Number
        }
    ]
});
module.exports = mongoose.model('mmmeC16', mmmeC16Schema);