'use strict'//usar novedades de JS

var mongoose = require('mongoose');//modulo de moongose
var Schema = mongoose.Schema;//Schema carga moongoose.Schema esto permite definir nuevos esquemas

var mmmeC20Schema = Schema({//esquema de la estructura que va a tener el formulario
    date_created: { type: Date, required: true },
    //datos tren
    noInspeccion: { type: String },
    noTren: { type: String },
    kilometraje: { type: String },
    horaInicio: { type: String },
    horaTerminacion: { type: String },
    
    operario1Dm1: { type: String, required: true},
    id_worker1Dm1: {type: String},
    operario2Dm1: { type: String, required: true},
    id_worker2Dm1: {type: String},
    operario1Dr: { type: String, required: true},
    id_worker1Dr: {type: String},
    operario2Dr: { type: String, required: true},
    id_worker2Dr: {type: String},
    operario1Dm2: { type: String, required: true},
    id_worker1Dm2: {type: String},
    operario2Dm2: { type: String, required: true},
    id_worker2Dm2: {type: String},
    operario1MMm1: { type: String, required: true},
    id_worker1MMm1: {type: String},
    operario2MMm1: { type: String, required: true},
    id_worker2MMm1: {type: String},
    operario1MMr: { type: String, required: true},
    id_worker1MMr: {type: String},
    operario2MMr: { type: String, required: true},
    id_worker2MMr: {type: String},
    operario1MMm2: { type: String, required: true},
    id_worker1MMm2: {type: String},
    operario2MMm2: { type: String, required: true},
    id_worker2MMm2: {type: String},
    unidad: { type: Number, required: true },

    //M1 EJE 1 y 2
    palancaIm1e1Rev: Boolean,
    palancaIm1e1Limp: Boolean,
    palancaIm1e1Eng: Boolean,
    palancaIm1e2Rev: Boolean,
    palancaIm1e2Limp: Boolean,
    palancaIm1e2Eng: Boolean,
    observacionesPi: String,

    palancaDm1e1Rev: Boolean,
    palancaDm1e1Limp: Boolean,
    palancaDm1e1Eng: Boolean,
    palancaDm1e2Rev: Boolean,
    palancaDm1e2Limp: Boolean,
    palancaDm1e2Eng: Boolean,
    observacionesPd: String,

    tirantem1e1Rev: Boolean,
    tirantem1e1Limp: Boolean,
    tirantem1e1Eng: Boolean,
    tirantem1e2Rev: Boolean,
    tirantem1e2Limp: Boolean,
    tirantem1e2Eng: Boolean,
    observacionesT: String,

    portazapataIm1e1Rev: Boolean,
    portazapataIm1e1Limp: Boolean,
    portazapataIm1e1Eng: Boolean,
    portazapataIm1e2Rev: Boolean,
    portazapataIm1e2Limp: Boolean,
    portazapataIm1e2Eng: Boolean,
    observacionesPtaI: String,

    casquilloIm1e1Rev: Boolean,
    casquilloIm1e1Limp: Boolean,
    casquilloIm1e1Eng: Boolean,
    casquilloIm1e2Rev: Boolean,
    casquilloIm1e2Limp: Boolean,
    casquilloIm1e2Eng: Boolean,
    observacionesCi: String,

    muelleIm1e1Rev: Boolean,
    muelleIm1e1Limp: Boolean,
    muelleIm1e1Eng: Boolean,
    muelleIm1e2Rev: Boolean,
    muelleIm1e2Limp: Boolean,
    muelleIm1e2Eng: Boolean,
    observacionesMi: String,

    remIm1e1Rev: Boolean,
    remIm1e1Limp: Boolean,
    remIm1e1Eng: Boolean,
    remIm1e2Rev: Boolean,
    remIm1e2Limp: Boolean,
    remIm1e2Eng: Boolean,
    observacionesRi: String,

    portazapataDm1e1Rev: Boolean,
    portazapataDm1e1Limp: Boolean,
    portazapataDm1e1Eng: Boolean,
    portazapataDm1e2Rev: Boolean,
    portazapataDm1e2Limp: Boolean,
    portazapataDm1e2Eng: Boolean,
    observacionesPtad: String,

    casquilloDm1e1Rev: Boolean,
    casquilloDm1e1Limp: Boolean,
    casquilloDm1e1Eng: Boolean,
    casquilloDm1e2Rev: Boolean,
    casquilloDm1e2Limp: Boolean,
    casquilloDm1e2Eng: Boolean,
    observacionesCd: String,

    muelleDm1e1Rev: Boolean,
    muelleDm1e1Limp: Boolean,
    muelleDm1e1Eng: Boolean,
    muelleDm1e2Rev: Boolean,
    muelleDm1e2Limp: Boolean,
    muelleDm1e2Eng: Boolean,
    observacionesMd: String,

    remDm1e1Rev: Boolean,
    remDm1e1Limp: Boolean,
    remDm1e1Eng: Boolean,
    remDm1e2Rev: Boolean,
    remDm1e2Limp: Boolean,
    remDm1e2Eng: Boolean,
    observacionesRd: String,

    bielam1e1Rev: Boolean,
    bielam1e1Limp: Boolean,
    bielam1e1Eng: Boolean,
    bielam1e2Rev: Boolean,
    bielam1e2Limp: Boolean,
    bielam1e2Eng: Boolean,
    observacionesB: String,

    bulones6m1e1Rev: Boolean,
    bulones6m1e1Limp: Boolean,
    bulones6m1e1Eng: Boolean,
    bulones6m1e2Rev: Boolean,
    bulones6m1e2Limp: Boolean,
    bulones6m1e2Eng: Boolean,
    observacionesB6: String,

    bulon2m1e1Rev: Boolean,
    bulon2m1e1Limp: Boolean,
    bulon2m1e1Eng: Boolean,
    bulon2m1e2Rev: Boolean,
    bulon2m1e2Limp: Boolean,
    bulon2m1e2Eng: Boolean,
    observacionesB2: String,

    casquillom1e1Rev: Boolean,
    casquillom1e1Limp: Boolean,
    casquillom1e1Eng: Boolean,
    casquillom1e2Rev: Boolean,
    casquillom1e2Limp: Boolean,
    casquillom1e2Eng: Boolean,
    observacionesC: String,

    //REMOLQUE EJES 1 y 2
    palancaFIrE1Rev: Boolean,
    palancaFIrE1Limp: Boolean,
    palancaFIrE1Eng: Boolean,
    palancaFIrE2Rev: Boolean,
    palancaFIrE2Limp: Boolean,
    palancaFIrE2Eng: Boolean,
    observacionesPfi: String,

    palancaFDrE1Rev: Boolean,
    palancaFDrE1Limp: Boolean,
    palancaFDrE1Eng: Boolean,
    palancaFDrE2Rev: Boolean,
    palancaFDrE2Limp: Boolean,
    palancaFDrE2Eng: Boolean,
    observacionesPfd: String,

    tiranterE1Rev: Boolean,
    tiranterE1Limp: Boolean,
    tiranterE1Eng: Boolean,
    tiranterE2Rev: Boolean,
    tiranterE2Limp: Boolean,
    tiranterE2Eng: Boolean,
    observacionesTirant: String,

    portazapataIzqrE1Rev: Boolean,
    portazapataIzqrE1Limp: Boolean,
    portazapataIzqrE1Eng: Boolean,
    portazapataIzqrE2Rev: Boolean,
    portazapataIzqrE2Limp: Boolean,
    portazapataIzqrE2Eng: Boolean,
    observacionesPizq: String,

    casquilloIzqrE1Rev: Boolean,
    casquilloIzqrE1Limp: Boolean,
    casquilloIzqrE1Eng: Boolean,
    casquilloIzqrE2Rev: Boolean,
    casquilloIzqrE2Limp: Boolean,
    casquilloIzqrE2Eng: Boolean,
    observacionesCizq: String,

    muellePIrE1Rev: Boolean,
    muellePIrE1Limp: Boolean,
    muellePIrE1Eng: Boolean,
    muellePIrE2Rev: Boolean,
    muellePIrE2Limp: Boolean,
    muellePIrE2Eng: Boolean,
    observacionesMpi: String,

    remPIrE1Rev: Boolean,
    remPIrE1Limp: Boolean,
    remPIrE1Eng: Boolean,
    remPIrE2Rev: Boolean,
    remPIrE2Limp: Boolean,
    remPIrE2Eng: Boolean,
    observacionesRpi: String,

    portazapataDerrE1Rev: Boolean,
    portazapataDerrE1Limp: Boolean,
    portazapataDerrE1Eng: Boolean,
    portazapataDerrE2Rev: Boolean,
    portazapataDerrE2Limp: Boolean,
    portazapataDerrE2Eng: Boolean,
    observacionesPder: String,

    casquilloDerrE1Rev: Boolean,
    casquilloDerrE1Limp: Boolean,
    casquilloDerrE1Eng: Boolean,
    casquilloDerrE2Rev: Boolean,
    casquilloDerrE2Limp: Boolean,
    casquilloDerrE2Eng: Boolean,
    observacionesCder: String,

    muellePDrE1Rev: Boolean,
    muellePDrE1Limp: Boolean,
    muellePDrE1Eng: Boolean,
    muellePDrE2Rev: Boolean,
    muellePDrE2Limp: Boolean,
    muellePDrE2Eng: Boolean,
    observacionesMpd: String,

    remPDrE1Rev: Boolean,
    remPDrE1Limp: Boolean,
    remPDrE1Eng: Boolean,
    remPDrE2Rev: Boolean,
    remPDrE2Limp: Boolean,
    remPDrE2Eng: Boolean,
    observacionesRpd: String,

    bielaDrE1Rev: Boolean,
    bielaDrE1Limp: Boolean,
    bielaDrE1Eng: Boolean,
    bielaDrE2Rev: Boolean,
    bielaDrE2Limp: Boolean,
    bielaDrE2Eng: Boolean,
    observacionesBd: String,

    bulones6rE1Rev: Boolean,
    bulones6rE1Limp: Boolean,
    bulones6rE1Eng: Boolean,
    bulones6rE2Rev: Boolean,
    bulones6rE2Limp: Boolean,
    bulones6rE2Eng: Boolean,
    observacionesBul6: String,

    bulonR2rE1Rev: Boolean,
    bulonR2rE1Limp: Boolean,
    bulonR2rE1Eng: Boolean,
    bulonR2rE2Rev: Boolean,
    bulonR2rE2Limp: Boolean,
    bulonR2rE2Eng: Boolean,
    observacionesBr2: String,

    casquilloCrE1Rev: Boolean,
    casquilloCrE1Limp: Boolean,
    casquilloCrE1Eng: Boolean,
    casquilloCrE2Rev: Boolean,
    casquilloCrE2Limp: Boolean,
    casquilloCrE2Eng: Boolean,
    observacionesCc: String,

    //M2 EJE 1 y 2
    palancaFIzqm2E1Rev: Boolean,
    palancaFIzqm2E1Limp: Boolean,
    palancaFIzqm2E1Eng: Boolean,
    palancaFIzqm2E2Rev: Boolean,
    palancaFIzqm2E2Limp: Boolean,
    palancaFIzqm2E2Eng: Boolean,
    observacionesPfizq: String,

    palancaFDerm2E1Rev: Boolean,
    palancaFDerm2E1Limp: Boolean,
    palancaFDerm2E1Eng: Boolean,
    palancaFDerm2E2Rev: Boolean,
    palancaFDerm2E2Limp: Boolean,
    palancaFDerm2E2Eng: Boolean,
    observacionesPfder: String,

    tirantem2E1Rev: Boolean,
    tirantem2E1Limp: Boolean,
    tirantem2E1Eng: Boolean,
    tirantem2E2Rev: Boolean,
    tirantem2E2Limp: Boolean,
    tirantem2E2Eng: Boolean,
    observacionesTirante: String,

    portazapataIzqm2E1Rev: Boolean,
    portazapataIzqm2E1Limp: Boolean,
    portazapataIzqm2E1Eng: Boolean,
    portazapataIzqm2E2Rev: Boolean,
    portazapataIzqm2E2Limp: Boolean,
    portazapataIzqm2E2Eng: Boolean,
    observacionesPtaIzq: String,

    casquilloPIzqm2E1Rev: Boolean,
    casquilloPIzqm2E1Limp: Boolean,
    casquilloPIzqm2E1Eng: Boolean,
    casquilloPIzqm2E2Rev: Boolean,
    casquilloPIzqm2E2Limp: Boolean,
    casquilloPIzqm2E2Eng: Boolean,
    observacionesCpIzq: String,

    muelleCPIm2E1Rev: Boolean,
    muelleCPIm2E1Limp: Boolean,
    muelleCPIm2E1Eng: Boolean,
    muelleCPIm2E2Rev: Boolean,
    muelleCPIm2E2Limp: Boolean,
    muelleCPIm2E2Eng: Boolean,
    observacionesMcpi: String,

    remAPIm2E1Rev: Boolean,
    remAPIm2E1Limp: Boolean,
    remAPIm2E1Eng: Boolean,
    remAPIm2E2Rev: Boolean,
    remAPIm2E2Limp: Boolean,
    remAPIm2E2Eng: Boolean,
    observacionesRapi: String,

    portazapataDm2E1Rev: Boolean,
    portazapataDm2E1Limp: Boolean,
    portazapataDm2E1Eng: Boolean,
    portazapataDm2E2Rev: Boolean,
    portazapataDm2E2Limp: Boolean,
    portazapataDm2E2Eng: Boolean,
    observacionesPtaDer: String,

    casquilloPDm2E1Rev: Boolean,
    casquilloPDm2E1Limp: Boolean,
    casquilloPDm2E1Eng: Boolean,
    casquilloPDm2E2Rev: Boolean,
    casquilloPDm2E2Limp: Boolean,
    casquilloPDm2E2Eng: Boolean,
    observacionesCpDer: String,

    muelleCPDm2E1Rev: Boolean,
    muelleCPDm2E1Limp: Boolean,
    muelleCPDm2E1Eng: Boolean,
    muelleCPDm2E2Rev: Boolean,
    muelleCPDm2E2Limp: Boolean,
    muelleCPDm2E2Eng: Boolean,
    observacionesMcpd: String,

    remAPDm2E1Rev: Boolean,
    remAPDm2E1Limp: Boolean,
    remAPDm2E1Eng: Boolean,
    remAPDm2E2Rev: Boolean,
    remAPDm2E2Limp: Boolean,
    remAPDm2E2Eng: Boolean,
    observacionesRapd: String,

    bielaDm2E1Rev: Boolean,
    bielaDm2E1Limp: Boolean,
    bielaDm2E1Eng: Boolean,
    bielaDm2E2Rev: Boolean,
    bielaDm2E2Limp: Boolean,
    bielaDm2E2Eng: Boolean,
    observacionesBdir: String,

    bulones6m2E1Rev: Boolean,
    bulones6m2E1Limp: Boolean,
    bulones6m2E1Eng: Boolean,
    bulones6m2E2Rev: Boolean,
    bulones6m2E2Limp: Boolean,
    bulones6m2E2Eng: Boolean,
    observacionesBulones6: String,

    bulonR2m2E1Rev: Boolean,
    bulonR2m2E1Limp: Boolean,
    bulonR2m2E1Eng: Boolean,
    bulonR2m2E2Rev: Boolean,
    bulonR2m2E2Limp: Boolean,
    bulonR2m2E2Eng: Boolean,
    observacionesBrt2: String,

    casquilloCm2E1Rev: Boolean,
    casquilloCm2E1Limp: Boolean,
    casquilloCm2E1Eng: Boolean,
    casquilloCm2E2Rev: Boolean,
    casquilloCm2E2Limp: Boolean,
    casquilloCm2E2Eng: Boolean,
    observacionesCasqC: String,

    observaciones: String,

    //material utilizado
    materialUtilizado: {
        numberOfMaterial: Number,    
        arr: [{
            _id: String,
            code: String,
            description: String,
            voucherNumber: String,
            quantity: String,
        }]
    },

    documentFormCurrentState: {
        approvalByWorker    : { id_worker: String, checked: Boolean },
        approvalBySupervisor: { id_worker: String, checked: Boolean },
        approvalByMannager  : { id_worker: String, checked: Boolean },
        loading: Boolean
    },

    historyFile: [
        {
            id_worker: String,
            workerName: String,
            editDate: Date,
            editValue: Number
        }
    ]
});
module.exports = mongoose.model('mmmeC20', mmmeC20Schema);