'use strict'//usar novedades de JS

var mongoose = require('mongoose');//modulo de moongose
var Schema = mongoose.Schema;//Schema carga moongoose.Schema esto permite definir nuevos esquemas

var mmmeC01Schema = Schema({//esquema de la estructura que va a tener el formularios
    date_created: { type: Date, required: true },
    //datos tren
    noInspeccion: { type: String },
    noTren: { type: String },
    kilometraje: { type: String },
    horaInicio: { type: String },
    horaTerminacion: { type: String },
    
    operario: { type: String, required: true},
    id_worker: {type: String},
    unidad: { type: Number, required: true },

    piston1m1L1: Boolean,
    piston1m1A1: Boolean,
    piston1m1L2: Boolean,
    piston1m1A2: Boolean,
    piston1m1L3: Boolean,
    piston1m1A3: Boolean,
    piston1m1L4: Boolean,
    piston1m1A4: Boolean,
    piston1m1L5: Boolean,
    piston1m1A5: Boolean,
    piston1m1L6: Boolean,
    piston1m1A6: Boolean,
    piston1m2L1: Boolean,
    piston1m2A1: Boolean,
    piston1m2L2: Boolean,
    piston1m2A2: Boolean,
    piston1m2L3: Boolean,
    piston1m2A3: Boolean,
    piston1m2L4: Boolean,
    piston1m2A4: Boolean,
    piston1m2L5: Boolean,
    piston1m2A5: Boolean,
    piston1m2L6: Boolean,
    piston1m2A6: Boolean,
    
    esprea1m1L1: Boolean,
    esprea1m1A1: Boolean,
    esprea1m1L2: Boolean,
    esprea1m1A2: Boolean,
    esprea1m1L3: Boolean,
    esprea1m1A3: Boolean,
    esprea1m1L4: Boolean,
    esprea1m1A4: Boolean,
    esprea1m1L5: Boolean,
    esprea1m1A5: Boolean,
    esprea1m1L6: Boolean,
    esprea1m1A6: Boolean,
    esprea1m2L1: Boolean,
    esprea1m2A1: Boolean,
    esprea1m2L2: Boolean,
    esprea1m2A2: Boolean,
    esprea1m2L3: Boolean,
    esprea1m2A3: Boolean,
    esprea1m2L4: Boolean,
    esprea1m2A4: Boolean,
    esprea1m2L5: Boolean,
    esprea1m2A5: Boolean,
    esprea1m2L6: Boolean,
    esprea1m2A6: Boolean,
    
    piston2m1L1: Boolean,
    piston2m1A1: Boolean,
    piston2m1L2: Boolean,
    piston2m1A2: Boolean,
    piston2m1L3: Boolean,
    piston2m1A3: Boolean,
    piston2m1L4: Boolean,
    piston2m1A4: Boolean,
    piston2m1L5: Boolean,
    piston2m1A5: Boolean,
    piston2m1L6: Boolean,
    piston2m1A6: Boolean,
    piston2m2L1: Boolean,
    piston2m2A1: Boolean,
    piston2m2L2: Boolean,
    piston2m2A2: Boolean,
    piston2m2L3: Boolean,
    piston2m2A3: Boolean,
    piston2m2L4: Boolean,
    piston2m2A4: Boolean,
    piston2m2L5: Boolean,
    piston2m2A5: Boolean,
    piston2m2L6: Boolean,
    piston2m2A6: Boolean,
    
    esprea2m1L1: Boolean,
    esprea2m1A1: Boolean,
    esprea2m1L2: Boolean,
    esprea2m1A2: Boolean,
    esprea2m1L3: Boolean,
    esprea2m1A3: Boolean,
    esprea2m1L4: Boolean,
    esprea2m1A4: Boolean,
    esprea2m1L5: Boolean,
    esprea2m1A5: Boolean,
    esprea2m1L6: Boolean,
    esprea2m1A6: Boolean,
    esprea2m2L1: Boolean,
    esprea2m2A1: Boolean,
    esprea2m2L2: Boolean,
    esprea2m2A2: Boolean,
    esprea2m2L3: Boolean,
    esprea2m2A3: Boolean,
    esprea2m2L4: Boolean,
    esprea2m2A4: Boolean,
    esprea2m2L5: Boolean,
    esprea2m2A5: Boolean,
    esprea2m2L6: Boolean,
    esprea2m2A6: Boolean,
    
    valvula1m1L1: Boolean,
    valvula1m1A1: Boolean,
    valvula1m1L2: Boolean,
    valvula1m1A2: Boolean,
    valvula1m1L3: Boolean,
    valvula1m1A3: Boolean,
    valvula1m1L4: Boolean,
    valvula1m1A4: Boolean,
    valvula1m1L5: Boolean,
    valvula1m1A5: Boolean,
    valvula1m1L6: Boolean,
    valvula1m1A6: Boolean,
    valvula1m2L1: Boolean,
    valvula1m2A1: Boolean,
    valvula1m2L2: Boolean,
    valvula1m2A2: Boolean,
    valvula1m2L3: Boolean,
    valvula1m2A3: Boolean,
    valvula1m2L4: Boolean,
    valvula1m2A4: Boolean,
    valvula1m2L5: Boolean,
    valvula1m2A5: Boolean,
    valvula1m2L6: Boolean,
    valvula1m2A6: Boolean,
    
    valvula2m1L1: Boolean,
    valvula2m1A1: Boolean,
    valvula2m1L2: Boolean,
    valvula2m1A2: Boolean,
    valvula2m1L3: Boolean,
    valvula2m1A3: Boolean,
    valvula2m1L4: Boolean,
    valvula2m1A4: Boolean,
    valvula2m1L5: Boolean,
    valvula2m1A5: Boolean,
    valvula2m1L6: Boolean,
    valvula2m1A6: Boolean,
    valvula2m2L1: Boolean,
    valvula2m2A1: Boolean,
    valvula2m2L2: Boolean,
    valvula2m2A2: Boolean,
    valvula2m2L3: Boolean,
    valvula2m2A3: Boolean,
    valvula2m2L4: Boolean,
    valvula2m2A4: Boolean,
    valvula2m2L5: Boolean,
    valvula2m2A5: Boolean,
    valvula2m2L6: Boolean,
    valvula2m2A6: Boolean,

    nivelAceiteM1: String,
    nivelAceiteM2: String,

    //GENERALES PARA TE-90, TE-95 y TE-06
    mangueraEm1R1: Boolean,
    mangueraEm1A1: Boolean,
    mangueraEm1R2: Boolean,
    mangueraEm1A2: Boolean,
    mangueraEm1R3: Boolean,
    mangueraEm1A3: Boolean,
    mangueraEm1R4: Boolean,
    mangueraEm1A4: Boolean,
    mangueraEm1R5: Boolean,
    mangueraEm1A5: Boolean,
    mangueraEm1R6: Boolean,
    mangueraEm1A6: Boolean,
    mangueraEm2R1: Boolean,
    mangueraEm2A1: Boolean,
    mangueraEm2R2: Boolean,
    mangueraEm2A2: Boolean,
    mangueraEm2R3: Boolean,
    mangueraEm2A3: Boolean,
    mangueraEm2R4: Boolean,
    mangueraEm2A4: Boolean,
    mangueraEm2R5: Boolean,
    mangueraEm2A5: Boolean, 
    mangueraEm2R6: Boolean,
    mangueraEm2A6: Boolean,
    
    mangueraSm1R1: Boolean,
    mangueraSm1A1: Boolean,
    mangueraSm1R2: Boolean,
    mangueraSm1A2: Boolean,
    mangueraSm1R3: Boolean,
    mangueraSm1A3: Boolean,
    mangueraSm1R4: Boolean,
    mangueraSm1A4: Boolean,
    mangueraSm1R5: Boolean,
    mangueraSm1A5: Boolean,
    mangueraSm1R6: Boolean,
    mangueraSm1A6: Boolean,
    mangueraSm2R1: Boolean,
    mangueraSm2A1: Boolean,
    mangueraSm2R2: Boolean,
    mangueraSm2A2: Boolean,
    mangueraSm2R3: Boolean,
    mangueraSm2A3: Boolean,
    mangueraSm2R4: Boolean,
    mangueraSm2A4: Boolean,
    mangueraSm2R5: Boolean,
    mangueraSm2A5: Boolean, 
    mangueraSm2R6: Boolean,
    mangueraSm2A6: Boolean,
    
    tornilloAm1R1: Boolean,
    tornilloAm1A1: Boolean,
    tornilloAm1R2: Boolean,
    tornilloAm1A2: Boolean,
    tornilloAm1R3: Boolean,
    tornilloAm1A3: Boolean,
    tornilloAm1R4: Boolean,
    tornilloAm1A4: Boolean,
    tornilloAm1R5: Boolean,
    tornilloAm1A5: Boolean,
    tornilloAm1R6: Boolean,
    tornilloAm1A6: Boolean,
    tornilloAm2R1: Boolean,
    tornilloAm2A1: Boolean,
    tornilloAm2R2: Boolean,
    tornilloAm2A2: Boolean,
    tornilloAm2R3: Boolean,
    tornilloAm2A3: Boolean,
    tornilloAm2R4: Boolean,
    tornilloAm2A4: Boolean,
    tornilloAm2R5: Boolean,
    tornilloAm2A5: Boolean, 
    tornilloAm2R6: Boolean,
    tornilloAm2A6: Boolean,
    
    tornilloEm1R1: Boolean,
    tornilloEm1A1: Boolean,
    tornilloEm1R2: Boolean,
    tornilloEm1A2: Boolean,
    tornilloEm1R3: Boolean,
    tornilloEm1A3: Boolean,
    tornilloEm1R4: Boolean,
    tornilloEm1A4: Boolean,
    tornilloEm1R5: Boolean,
    tornilloEm1A5: Boolean,
    tornilloEm1R6: Boolean,
    tornilloEm1A6: Boolean,
    tornilloEm2R1: Boolean,
    tornilloEm2A1: Boolean,
    tornilloEm2R2: Boolean,
    tornilloEm2A2: Boolean,
    tornilloEm2R3: Boolean,
    tornilloEm2A3: Boolean,
    tornilloEm2R4: Boolean,
    tornilloEm2A4: Boolean,
    tornilloEm2R5: Boolean,
    tornilloEm2A5: Boolean, 
    tornilloEm2R6: Boolean,
    tornilloEm2A6: Boolean,

    observaciones: String,
    
    //material utilizado
    materialUtilizado: {
        numberOfMaterial: Number,    
        arr: [{
            _id: String,
            code: String,
            description: String,
            voucherNumber: String,
            quantity: String,
        }]
    },

    documentFormCurrentState: {
        approvalByWorker    : { id_worker: String, checked: Boolean },
        approvalBySupervisor: { id_worker: String, checked: Boolean },
        approvalByMannager  : { id_worker: String, checked: Boolean },
        loading: Boolean
    },

    historyFile: [
        {
            id_worker: String,
            workerName: String,
            editDate: Date,
            editValue: Number
        }
    ]
});
module.exports = mongoose.model('mmmeC01', mmmeC01Schema);