'use strict'//usar novedades de JS

var mongoose = require('mongoose');//modulo de moongose
var Schema = mongoose.Schema;//Schema carga moongoose.Schema esto permite definir nuevos esquemas

var mmmaM03Schema = Schema({//esquema de la estructura que va a tener el formulario
    date_created: { type: Date, required: true },
    //datos tren
    noInspeccion: { type: String },
    noTren: { type: String },
    kilometraje: { type: String },
    fechaInicio: { type: String },
    fechaTerminacion: { type: String },

    //1. DESMONTAJE COPETES DE VENTILACION DE PASAJEROS
    operario1: { type: String, required: true},
    id_worker1: {type: String},
    operario2: { type: String, required: true},
    id_worker2: {type: String},
    operario3: { type: String, required: true},
    id_worker3: {type: String},
    operario4: { type: String, required: true},
    id_worker4: {type: String},
    operario5: { type: String, required: true},
    id_worker5: {type: String},
    operario6: { type: String, required: true},
    id_worker6: {type: String},
    operario7: { type: String, required: true},
    id_worker7: {type: String},

    retirarTm11: Boolean,
    retirarTm12: Boolean,
    retirarTm13: Boolean,
    retirarTm14: Boolean,
    retirarTm21: Boolean,
    retirarTm22: Boolean,
    retirarTm23: Boolean,
    retirarTm24: Boolean,
    observacionesRt: String,

    retirarCm11: Boolean,
    retirarCm12: Boolean,
    retirarCm13: Boolean,
    retirarCm14: Boolean,
    retirarCm21: Boolean,
    retirarCm22: Boolean,
    retirarCm23: Boolean,
    retirarCm24: Boolean,
    observacionesRc: String,

    marcarPm11: Boolean,
    marcarPm12: Boolean,
    marcarPm13: Boolean,
    marcarPm14: Boolean,
    marcarPm21: Boolean,
    marcarPm22: Boolean,
    marcarPm23: Boolean,
    marcarPm24: Boolean,
    observacionesMp: String,

    bajarCm11: Boolean,
    bajarCm12: Boolean,
    bajarCm13: Boolean,
    bajarCm14: Boolean,
    bajarCm21: Boolean,
    bajarCm22: Boolean,
    bajarCm23: Boolean,
    bajarCm24: Boolean,
    observacionesBc: String,

    extraccionTm11: Boolean,
    extraccionTm12: Boolean,
    extraccionTm13: Boolean,
    extraccionTm14: Boolean,
    extraccionTm21: Boolean,
    extraccionTm22: Boolean,
    extraccionTm23: Boolean,
    extraccionTm24: Boolean,
    observacionesEt: String,

    //2. MANTENIMIENTO DE COPETES DE VENTILACION DE PASAJEROS
    operario8: { type: String, required: true},
    id_worker8: {type: String},
    operario9: { type: String, required: true},
    id_worker9: {type: String},
    operario10: { type: String, required: true},
    id_worker10: {type: String},

    limpiezaPm11: Boolean,
    limpiezaPm12: Boolean,
    limpiezaPm13: Boolean,
    limpiezaPm14: Boolean,
    limpiezaPm21: Boolean,
    limpiezaPm22: Boolean,
    limpiezaPm23: Boolean,
    limpiezaPm24: Boolean,
    observacionesLp: String,

    recuperacionZm11: Boolean,
    recuperacionZm12: Boolean,
    recuperacionZm13: Boolean,
    recuperacionZm14: Boolean,
    recuperacionZm21: Boolean,
    recuperacionZm22: Boolean,
    recuperacionZm23: Boolean,
    recuperacionZm24: Boolean,
    observacionesRz: String,

    recuperacionLm11: Boolean,
    recuperacionLm12: Boolean,
    recuperacionLm13: Boolean,
    recuperacionLm14: Boolean,
    recuperacionLm21: Boolean,
    recuperacionLm22: Boolean,
    recuperacionLm23: Boolean,
    recuperacionLm24: Boolean,
    observacionesRl: String,

    aplicacionPm11: Boolean,
    aplicacionPm12: Boolean,
    aplicacionPm13: Boolean,
    aplicacionPm14: Boolean,
    aplicacionPm21: Boolean,
    aplicacionPm22: Boolean,
    aplicacionPm23: Boolean,
    aplicacionPm24: Boolean,
    observacionesAp: String,

    aplicacionEm11: Boolean,
    aplicacionEm12: Boolean,
    aplicacionEm13: Boolean,
    aplicacionEm14: Boolean,
    aplicacionEm21: Boolean,
    aplicacionEm22: Boolean,
    aplicacionEm23: Boolean,
    aplicacionEm24: Boolean,
    observacionesAe: String,

    preparacionAm11: Boolean,
    preparacionAm12: Boolean,
    preparacionAm13: Boolean,
    preparacionAm14: Boolean,
    preparacionAm21: Boolean,
    preparacionAm22: Boolean,
    preparacionAm23: Boolean,
    preparacionAm24: Boolean,
    observacionesPa: String,

    aplicacionCm11: Boolean,
    aplicacionCm12: Boolean,
    aplicacionCm13: Boolean,
    aplicacionCm14: Boolean,
    aplicacionCm21: Boolean,
    aplicacionCm22: Boolean,
    aplicacionCm23: Boolean,
    aplicacionCm24: Boolean,
    observacionesAc: String,

    debastadoPm11: Boolean,
    debastadoPm12: Boolean,
    debastadoPm13: Boolean,
    debastadoPm14: Boolean,
    debastadoPm21: Boolean,
    debastadoPm22: Boolean,
    debastadoPm23: Boolean,
    debastadoPm24: Boolean,
    observacionesDp: String,

    preparacionAPm11: Boolean,
    preparacionAPm12: Boolean,
    preparacionAPm13: Boolean,
    preparacionAPm14: Boolean,
    preparacionAPm21: Boolean,
    preparacionAPm22: Boolean,
    preparacionAPm23: Boolean,
    preparacionAPm24: Boolean,
    observacionesPap: String,

    aplicacionCZm11: Boolean,
    aplicacionCZm12: Boolean,
    aplicacionCZm13: Boolean,
    aplicacionCZm14: Boolean,
    aplicacionCZm21: Boolean,
    aplicacionCZm22: Boolean,
    aplicacionCZm23: Boolean,
    aplicacionCZm24: Boolean,
    observacionesAcz: String,

    aplicacionPAm11: Boolean,
    aplicacionPAm12: Boolean,
    aplicacionPAm13: Boolean,
    aplicacionPAm14: Boolean,
    aplicacionPAm21: Boolean,
    aplicacionPAm22: Boolean,
    aplicacionPAm23: Boolean,
    aplicacionPAm24: Boolean,
    observacionesApa: String,

    aplicacionPTm11: Boolean,
    aplicacionPTm12: Boolean,
    aplicacionPTm13: Boolean,
    aplicacionPTm14: Boolean,
    aplicacionPTm21: Boolean,
    aplicacionPTm22: Boolean,
    aplicacionPTm23: Boolean,
    aplicacionPTm24: Boolean,
    observacionesApt: String,

    //3. MONTAJE DE COPETES DE VENTILACION DE PASAJEROS
    operario11: { type: String, required: true},
    id_worker11: {type: String},
    operario12: { type: String, required: true},
    id_worker12: {type: String},
    operario13: { type: String, required: true},
    id_worker13: {type: String},
    operario14: { type: String, required: true},
    id_worker14: {type: String},
    operario15: { type: String, required: true},
    id_worker15: {type: String},
    operario16: { type: String, required: true},
    id_worker16: {type: String},
    operario17: { type: String, required: true},
    id_worker17: {type: String},
    operario18: { type: String, required: true},
    id_worker18: {type: String},
    unidad: { type: Number, required: true },

    subirCm11: Boolean,
    subirCm12: Boolean,
    subirCm13: Boolean,
    subirCm14: Boolean,
    subirCm21: Boolean,
    subirCm22: Boolean,
    subirCm23: Boolean,
    subirCm24: Boolean,
    observacionesSc: String,

    alinearCEm11: Boolean,
    alinearCEm12: Boolean,
    alinearCEm13: Boolean,
    alinearCEm14: Boolean,
    alinearCEm21: Boolean,
    alinearCEm22: Boolean,
    alinearCEm23: Boolean,
    alinearCEm24: Boolean,
    observacionesAce: String,

    colocarTm11: Boolean,
    colocarTm12: Boolean,
    colocarTm13: Boolean,
    colocarTm14: Boolean,
    colocarTm21: Boolean,
    colocarTm22: Boolean,
    colocarTm23: Boolean,
    colocarTm24: Boolean,
    observacionesCt: String,

    observaciones: String,

    //MATERIAL UTILIZADO
    materialUtilizado: {
        numberOfMaterial: Number,    
        arr: [{
            _id: String,
            code: String,
            description: String,
            voucherNumber: String,
            quantity: String,
        }]
    },

    documentFormCurrentState: {
        approvalByWorker    : { id_worker: String, checked: Boolean },
        approvalBySupervisor: { id_worker: String, checked: Boolean },
        approvalByMannager  : { id_worker: String, checked: Boolean },
        loading: Boolean
    },

    historyFile: [
        {
            id_worker: String,
            workerName: String,
            editDate: Date,
            editValue: Number
        }
    ]
});
module.exports = mongoose.model('mmmaM03', mmmaM03Schema);