const mongoose = require('mongoose');
const {Schema} = mongoose;

const memaM16Schema = new Schema({

    trainModel: { type: String, required: true },//tren programado
    kilometraje: { type: Number },
    
    date_inicio: { type: String },
    date_termino: { type: String },
    
    dateultmant: { type: String },
    datepromant: { type: String },

    date_created: { type: Date, required: true },
    user:{ type: String, required: true },
    id_worker: {type: String, required: true},
    obs1: String,
     //----------------------------

     //Luminarias lado derecho M1

     m1l1d: String,
     m1dl1d: String,
     m1tc1d: String,
     m1bt1d: String,
     m1tf1d: String,
     m1bw1d: String,
     m1t81d: String,
     m1p81d: String,
     m1tw1d: String,
     m1t1d: String,

     m1l2d: String,
     m1dl2d: String,
     m1tc2d: String,
     m1bt2d: String,
     m1tf2d: String,
     m1bw2d: String,
     m1t82d: String,
     m1p82d: String,
     m1tw2d: String,
     m1t2d: String,

     m1l3d: String,
     m1dl3d: String,
     m1tc3d: String,
     m1bt3d: String,
     m1tf3d: String,
     m1bw3d: String,
     m1t83d: String,
     m1p83d: String,
     m1tw3d: String,
     m1t3d: String,

     m1l4d: String,
     m1dl4d: String,
     m1tc4d: String,
     m1bt4d: String,
     m1tf4d: String,
     m1bw4d: String,
     m1t84d: String,
     m1p84d: String,
     m1tw4d: String,
     m1t4d: String,

     m1l5d: String,
     m1dl5d: String,
     m1tc5d: String,
     m1bt5d: String,
     m1tf5d: String,
     m1bw5d: String,
     m1t85d: String,
     m1p85d: String,
     m1tw5d: String,
     m1t5d: String,

     m1l6d: String,
     m1dl6d: String,
     m1tc6d: String,
     m1bt6d: String,
     m1tf6d: String,
     m1bw6d: String,
     m1t86d: String,
     m1p86d: String,
     m1tw6d: String,
     m1t6d: String,

     m1l7d: String,
     m1dl7d: String,
     m1tc7d: String,
     m1bt7d: String,
     m1tf7d: String,
     m1bw7d: String,
     m1t87d: String,
     m1p87d: String,
     m1tw7d: String,
     m1t7d: String,

     m1l8d: String,
     m1dl8d: String,
     m1tc8d: String,
     m1bt8d: String,
     m1tf8d: String,
     m1bw8d: String,
     m1t88d: String,
     m1p88d: String,
     m1tw8d: String,
     m1t8d: String,

     m1l9d: String,
     m1dl9d: String,
     m1tc9d: String,
     m1bt9d: String,
     m1tf9d: String,
     m1bw9d: String,
     m1t89d: String,
     m1p89d: String,
     m1tw9d: String,
     m1t9d: String,

     //Luminarias lado izq M1

     m1l1i: String,
     m1dl1i: String,
     m1tc1i: String,
     m1bt1i: String,
     m1tf1i: String,
     m1bw1i: String,
     m1t81i: String,
     m1p81i: String,
     m1tw1i: String,
     m1t1i: String,

     m1l2i: String,
     m1dl2i: String,
     m1tc2i: String,
     m1bt2i: String,
     m1tf2i: String,
     m1bw2i: String,
     m1t82i: String,
     m1p82i: String,
     m1tw2i: String,
     m1t2i: String,

     m1l3i: String,
     m1dl3i: String,
     m1tc3i: String,
     m1bt3i: String,
     m1tf3i: String,
     m1bw3i: String,
     m1t83i: String,
     m1p83i: String,
     m1tw3i: String,
     m1t3i: String,

     m1l4i: String,
     m1dl4i: String,
     m1tc4i: String,
     m1bt4i: String,
     m1tf4i: String,
     m1bw4i: String,
     m1t84i: String,
     m1p84i: String,
     m1tw4i: String,
     m1t4i: String,

     m1l5i: String,
     m1dl5i: String,
     m1tc5i: String,
     m1bt5i: String,
     m1tf5i: String,
     m1bw5i: String,
     m1t85i: String,
     m1p85i: String,
     m1tw5i: String,
     m1t5i: String,

     m1l6i: String,
     m1dl6i: String,
     m1tc6i: String,
     m1bt6i: String,
     m1tf6i: String,
     m1bw6i: String,
     m1t86i: String,
     m1p86i: String,
     m1tw6i: String,
     m1t6i: String,

     m1l7i: String,
     m1dl7i: String,
     m1tc7i: String,
     m1bt7i: String,
     m1tf7i: String,
     m1bw7i: String,
     m1t87i: String,
     m1p87i: String,
     m1tw7i: String,
     m1t7i: String,

     m1l8i: String,
     m1dl8i: String,
     m1tc8i: String,
     m1bt8i: String,
     m1tf8i: String,
     m1bw8i: String,
     m1t88i: String,
     m1p88i: String,
     m1tw8i: String,
     m1t8i: String,

     m1l9i: String,
     m1dl9i: String,
     m1tc9i: String,
     m1bt9i: String,
     m1tf9i: String,
     m1bw9i: String,
     m1t89i: String,
     m1p89i: String,
     m1tw9i: String,
     m1t9i: String,

     obs2: String,

          //Luminarias lado derecho M2

          m2l1d: String,
          m2dl1d: String,
          m2tc1d: String,
          m2bt1d: String,
          m2tf1d: String,
          m2bw1d: String,
          m2t81d: String,
          m2p81d: String,
          m2tw1d: String,
          m2t1d: String,
     
          m2l2d: String,
          m2dl2d: String,
          m2tc2d: String,
          m2bt2d: String,
          m2tf2d: String,
          m2bw2d: String,
          m2t82d: String,
          m2p82d: String,
          m2tw2d: String,
          m2t2d: String,
     
          m2l3d: String,
          m2dl3d: String,
          m2tc3d: String,
          m2bt3d: String,
          m2tf3d: String,
          m2bw3d: String,
          m2t83d: String,
          m2p83d: String,
          m2tw3d: String,
          m2t3d: String,
     
          m2l4d: String,
          m2dl4d: String,
          m2tc4d: String,
          m2bt4d: String,
          m2tf4d: String,
          m2bw4d: String,
          m2t84d: String,
          m2p84d: String,
          m2tw4d: String,
          m2t4d: String,
     
          m2l5d: String,
          m2dl5d: String,
          m2tc5d: String,
          m2bt5d: String,
          m2tf5d: String,
          m2bw5d: String,
          m2t85d: String,
          m2p85d: String,
          m2tw5d: String,
          m2t5d: String,
     
          m2l6d: String,
          m2dl6d: String,
          m2tc6d: String,
          m2bt6d: String,
          m2tf6d: String,
          m2bw6d: String,
          m2t86d: String,
          m2p86d: String,
          m2tw6d: String,
          m2t6d: String,
     
          m2l7d: String,
          m2dl7d: String,
          m2tc7d: String,
          m2bt7d: String,
          m2tf7d: String,
          m2bw7d: String,
          m2t87d: String,
          m2p87d: String,
          m2tw7d: String,
          m2t7d: String,
     
          m2l8d: String,
          m2dl8d: String,
          m2tc8d: String,
          m2bt8d: String,
          m2tf8d: String,
          m2bw8d: String,
          m2t88d: String,
          m2p88d: String,
          m2tw8d: String,
          m2t8d: String,
     
          m2l9d: String,
          m2dl9d: String,
          m2tc9d: String,
          m2bt9d: String,
          m2tf9d: String,
          m2bw9d: String,
          m2t89d: String,
          m2p89d: String,
          m2tw9d: String,
          m2t9d: String,
     
          //Luminarias lado izq m2
     
          m2l1i: String,
          m2dl1i: String,
          m2tc1i: String,
          m2bt1i: String,
          m2tf1i: String,
          m2bw1i: String,
          m2t81i: String,
          m2p81i: String,
          m2tw1i: String,
          m2t1i: String,
     
          m2l2i: String,
          m2dl2i: String,
          m2tc2i: String,
          m2bt2i: String,
          m2tf2i: String,
          m2bw2i: String,
          m2t82i: String,
          m2p82i: String,
          m2tw2i: String,
          m2t2i: String,
     
          m2l3i: String,
          m2dl3i: String,
          m2tc3i: String,
          m2bt3i: String,
          m2tf3i: String,
          m2bw3i: String,
          m2t83i: String,
          m2p83i: String,
          m2tw3i: String,
          m2t3i: String,
     
          m2l4i: String,
          m2dl4i: String,
          m2tc4i: String,
          m2bt4i: String,
          m2tf4i: String,
          m2bw4i: String,
          m2t84i: String,
          m2p84i: String,
          m2tw4i: String,
          m2t4i: String,
     
          m2l5i: String,
          m2dl5i: String,
          m2tc5i: String,
          m2bt5i: String,
          m2tf5i: String,
          m2bw5i: String,
          m2t85i: String,
          m2p85i: String,
          m2tw5i: String,
          m2t5i: String,
     
          m2l6i: String,
          m2dl6i: String,
          m2tc6i: String,
          m2bt6i: String,
          m2tf6i: String,
          m2bw6i: String,
          m2t86i: String,
          m2p86i: String,
          m2tw6i: String,
          m2t6i: String,
     
          m2l7i: String,
          m2dl7i: String,
          m2tc7i: String,
          m2bt7i: String,
          m2tf7i: String,
          m2bw7i: String,
          m2t87i: String,
          m2p87i: String,
          m2tw7i: String,
          m2t7i: String,
     
          m2l8i: String,
          m2dl8i: String,
          m2tc8i: String,
          m2bt8i: String,
          m2tf8i: String,
          m2bw8i: String,
          m2t88i: String,
          m2p88i: String,
          m2tw8i: String,
          m2t8i: String,
     
          m2l9i: String,
          m2dl9i: String,
          m2tc9i: String,
          m2bt9i: String,
          m2tf9i: String,
          m2bw9i: String,
          m2t89i: String,
          m2p89i: String,
          m2tw9i: String,
          m2t9i: String,
     
          obs3: String,
     

     //----------------------------
     equipolUtilizado: {
          numberOfEquipo: Number,    
          arr: [{
              numberOfequ: String,
              marca: String,
              inv: String,
          }]
          },
      
         //Materiales
         materialUtilizado: {
          numberOfMaterial: Number,    
          arr: [{
              _id: String,
              code: String,
              description: String,
              voucherNumber: String,
              quantity: String,
              unit: String
          }]
      },
      
      documentFormCurrentState: {
          approvalByWorker    : { id_worker: String, checked: Boolean },
          approvalBySupervisor: { id_worker: String, checked: Boolean },
          approvalByMannager  : { id_worker: String, checked: Boolean },
          loading: Boolean
      },
      historyFile: [
          {
              id_worker: String,
              workerName: String,
        
              editDate: Date,
              editValue: Number
          }
      ]
      
      });
      
      module.exports = mongoose.model('memaM16', memaM16Schema);
      