
const mongoose = require('mongoose');
const {Schema} = mongoose;

const memaM23Schema = new Schema({

    trainModel: { type: String, required: true },//tren programado
    kilometraje: { type: Number },
    
    date_inicio: { type: String },
    date_termino: { type: String },
    
    dateultmant: { type: String },
    datepromant: { type: String },

    date_created: { type: Date, required: true },
    user:{ type: String, required: true },
    id_worker: {type: String, required: true},
    obs1: String,

     //----------------------------

     //Aparatos de 24V
     cfpif: String,
     cfpl: String,
     cfpcf: String,
     cfpcm: String,
     cfpb: String,
     cfpr: String,

     cfeif: String,
     cfel: String,
     cfecf: String,
     cfecm: String,
     cfeb: String,
     cfer: String,

     cvif: String,
     cvl: String,
     cvcf: String,
     cvcm: String,
     cvb: String,
     cvr: String,

     cfsif: String,
     cfsl: String,
     cfscf: String,
     cfscm: String,
     cfsb: String,
     cfsr: String,

     catif: String,
     catl: String,
     catcf: String,
     catcm: String,
     catb: String,
     catr: String,

     cmeif: String,
     cmel: String,
     cmecf: String,
     cmecm: String,
     cmeb: String,
     cmer: String,

     rco1if: String,
     rco1l: String,
     rco1cf: String,
     rco1cm: String,
     rco1b: String,
     rco1r: String,

     rco2if: String,
     rco2l: String,
     rco2cf: String,
     rco2cm: String,
     rco2b: String,
     rco2r: String,

     radif: String,
     radl: String,
     radcf: String,
     radcm: String,
     radb: String,
     radr: String,

     ratif: String,
     ratl: String,
     ratcf: String,
     ratcm: String,
     ratb: String,
     ratr: String,

     gstfif: String,
     gstfl: String,
     gstfcf: String,
     gstfcm: String,
     gstfb: String,
     gstfr: String,

     obs2: String,

     //Aparatos de 220 V
     et1vif: String,
     et1vl: String,
     et1vcf: String,
     et1vcm: String,
     et1vb: String,
     et1vr: String,

     et2vif: String,
     et2vl: String,
     et2vcf: String,
     et2vcm: String,
     et2vb: String,
     et2vr: String,

     cv1if: String,
     cv1l: String,
     cv1cf: String,
     cv1cm: String,
     cv1b: String,
     cv1r: String,

     cv2if: String,
     cv2l: String,
     cv2cf: String,
     cv2cm: String,
     cv2b: String,
     cv2r: String,

     cvtif: String,
     cvtl: String,
     cvtcf: String,
     cvtcm: String,
     cvtb: String,
     cvtr: String,

     rt1if: String,
     rt1l: String,
     rt1cf: String,
     rt1cm: String,
     rt1b: String,
     rt1r: String,

     //Aparatos de Precarga
     dpfif: String,
     dpfl: String,
     dpfcf: String,
     dpfcm: String,
     dpfb: String,
     dpfr: String,

     tvlif: String,
     tvll: String,
     tvlcf: String,
     tvlcm: String,
     tvlb: String,
     tvlr: String,

     cpcif: String,
     cpcl: String,
     cpccf: String,
     cpccm: String,
     cpcb: String,
     cpcr: String,

     fus1if: String,
     fus1l: String,
     fus1cf: String,
     fus1cm: String,
     fus1b: String,
     fus1r: String,

     fus2if: String,
     fus2l: String,
     fus2cf: String,
     fus2cm: String,
     fus2b: String,
     fus2r: String,

     fus3if: String,
     fus3l: String,
     fus3cf: String,
     fus3cm: String,
     fus3b: String,
     fus3r: String,

     //Transductores
     tcfif: String,
     tcfl: String,
     tcfr: String,

     tcm1if: String,
     tcm1l: String,
     tcm1r: String,

     tcm2if: String,
     tcm2l: String,
     tcm2r: String,

     tvm1if: String,
     tvm1l: String,
     tvm1r: String,

     tvm2if: String,
     tvm2l: String,
     tvm2r: String,

     cutif: String,
     cutl: String,
     cutr: String,

     tvcif: String,
     tvcl: String,
     tvcr: String,

     obs3: String,

     //Aparatos de precarga
     cf1if: String,
     cf1l: String,
     cf1r: String,
     cf1p: String,

     cf2if: String,
     cf2l: String,
     cf2r: String,
     cf2p: String,

     cf3if: String,
     cf3l: String,
     cf3r: String,
     cf3p: String,

     cf4if: String,
     cf4l: String,
     cf4r: String,
     cf4p: String,

     cf5if: String,
     cf5l: String,
     cf5r: String,
     cf5p: String,

     cf6if: String,
     cf6l: String,
     cf6r: String,
     cf6p: String,

     rpfif: String,
     rpfl: String,
     rpfr: String,
     rpfp: String,

     rdf1if: String,
     rdf1l: String,
     rdf1r: String,
     rdf1p: String,

     rdf2if: String,
     rdf2l: String,
     rdf2r: String,
     rdf2p: String,

     iffif: String,
     iffl: String,
     iffr: String,
     iffp: String,

     flif: String,
     fll: String,
     flr: String,
     flp: String,

    obs4: String,
    
    //Aparatos para disyuntor
    cde1if: String,
    cde1l: String,
    cde1cf: String,
    cde1cm: String,
    cde1b: String,
    cde1r: String,

    cde3if: String,
    cde3l: String,
    cde3cf: String,
    cde3cm: String,
    cde3b: String,
    cde3r: String,

    cde2if: String,
    cde2l: String,
    cde2cf: String,
    cde2cm: String,
    cde2b: String,
    cde2r: String,

    rtde1if: String,
    rtde1l: String,
    rtde1cf: String,
    rtde1cm: String,
    rtde1b: String,
    rtde1r: String,

    rtde2if: String,
    rtde2l: String,
    rtde2cf: String,
    rtde2cm: String,
    rtde2b: String,
    rtde2r: String,

    obs5: String,

    //Circuito Principal de contactores BMS
    picrf1: String,
    picrf2: String,
    picrf3: String,
    pict1: String,
    pict2: String,
    pict3: String,
    picc1: String,
    picc2: String,
    picc3: String,
    picp1: String,
    picp2: String,
    picp3: String,

    pdcrf1: String,
    pdcrf2: String,
    pdcrf3: String,
    pdct1: String,
    pdct2: String,
    pdct3: String,
    pdcc1: String,
    pdcc2: String,
    pdcc3: String,
    pdcp1: String,
    pdcp2: String,
    pdcp3: String,

    mrcrf1: String,
    mrcrf2: String,
    mrcrf3: String,
    mrct1: String,
    mrct2: String,
    mrct3: String,
    mrcc1: String,
    mrcc2: String,
    mrcc3: String,
    mrcp1: String,
    mrcp2: String,
    mrcp3: String,

    pecrf1: String,
    pecrf2: String,
    pecrf3: String,
    pect1: String,
    pect2: String,
    pect3: String,
    pecc1: String,
    pecc2: String,
    pecc3: String,
    pecp1: String,
    pecp2: String,
    pecp3: String,

    ticrf1: String,
    ticrf2: String,
    ticrf3: String,
    tict1: String,
    tict2: String,
    tict3: String,
    ticc1: String,
    ticc2: String,
    ticc3: String,
    ticp1: String,
    ticp2: String,
    ticp3: String,

    tscrf1: String,
    tscrf2: String,
    tscrf3: String,
    tsct1: String,
    tsct2: String,
    tsct3: String,
    tscc1: String,
    tscc2: String,
    tscc3: String,
    tscp1: String,
    tscp2: String,
    tscp3: String,

    macrf1: String,
    macrf2: String,
    macrf3: String,
    mact1: String,
    mact2: String,
    mact3: String,
    macc1: String,
    macc2: String,
    macc3: String,
    macp1: String,
    macp2: String,
    macp3: String,

    pescrf1: String,
    pescrf2: String,
    pescrf3: String,
    pesct1: String,
    pesct2: String,
    pesct3: String,
    pescc1: String,
    pescc2: String,
    pescc3: String,
    pescp1: String,
    pescp2: String,
    pescp3: String,

    mpcrf1: String,
    mpcrf2: String,
    mpcrf3: String,
    mpct1: String,
    mpct2: String,
    mpct3: String,
    mpcc1: String,
    mpcc2: String,
    mpcc3: String,
    mpcp1: String,
    mpcp2: String,
    mpcp3: String,

    mpecrf1: String,
    mpecrf2: String,
    mpecrf3: String,
    mpect1: String,
    mpect2: String,
    mpect3: String,
    mpecc1: String,
    mpecc2: String,
    mpecc3: String,
    mpecp1: String,
    mpecp2: String,
    mpecp3: String,

    aicrf1: String,
    aicrf2: String,
    aicrf3: String,
    aict1: String,
    aict2: String,
    aict3: String,
    aicc1: String,
    aicc2: String,
    aicc3: String,
    aicp1: String,
    aicp2: String,
    aicp3: String,

    mplcrf1: String,
    mplcrf2: String,
    mplcrf3: String,
    mplct1: String,
    mplct2: String,
    mplct3: String,
    mplcc1: String,
    mplcc2: String,
    mplcc3: String,
    mplcp1: String,
    mplcp2: String,
    mplcp3: String,

    cocrf1: String,
    cocrf2: String,
    cocrf3: String,
    coct1: String,
    coct2: String,
    coct3: String,
    cocc1: String,
    cocc2: String,
    cocc3: String,
    cocp1: String,
    cocp2: String,
    cocp3: String,

    cpcrf1: String,
    cpcrf2: String,
    cpcrf3: String,
    cpct1: String,
    cpct2: String,
    cpct3: String,
    cpcc1: String,
    cpcc2: String,
    cpcc3: String,
    cpcp1: String,
    cpcp2: String,
    cpcp3: String,

    pccrf1: String,
    pccrf2: String,
    pccrf3: String,
    pcct1: String,
    pcct2: String,
    pcct3: String,
    pccc1: String,
    pccc2: String,
    pccc3: String,
    pccp1: String,
    pccp2: String,
    pccp3: String,

    m4crf1: String,
    m4crf2: String,
    m4crf3: String,
    m4ct1: String,
    m4ct2: String,
    m4ct3: String,
    m4cc1: String,
    m4cc2: String,
    m4cc3: String,
    m4cp1: String,
    m4cp2: String,
    m4cp3: String,

    apecrf1: String,
    apecrf2: String,
    apecrf3: String,
    apect1: String,
    apect2: String,
    apect3: String,
    apecc1: String,
    apecc2: String,
    apecc3: String,
    apecp1: String,
    apecp2: String,
    apecp3: String,

    cacrf1: String,
    cacrf2: String,
    cacrf3: String,
    cact1: String,
    cact2: String,
    cact3: String,
    cacc1: String,
    cacc2: String,
    cacc3: String,
    cacp1: String,
    cacp2: String,
    cacp3: String,

    ppcrf1: String,
    ppcrf2: String,
    ppcrf3: String,
    ppct1: String,
    ppct2: String,
    ppct3: String,
    ppcc1: String,
    ppcc2: String,
    ppcc3: String,
    ppcp1: String,
    ppcp2: String,
    ppcp3: String,

    ppecrf1: String,
    ppecrf2: String,
    ppecrf3: String,
    ppect1: String,
    ppect2: String,
    ppect3: String,
    ppecc1: String,
    ppecc2: String,
    ppecc3: String,
    ppecp1: String,
    ppecp2: String,
    ppecp3: String,

    obs6: String,

    //Dispositivos de cierre de contactore BMS
    a2302crf1: String,
    a2302crf2: String,
    a2302crf3: String,
    a2302ct1: String,
    a2302ct2: String,
    a2302ct3: String,
    a2302cc1: String,
    a2302cc2: String,
    a2302cc3: String,
    a2302cp1: String,
    a2302cp2: String,
    a2302cp3: String,

    p2303crf1: String,
    p2303crf2: String,
    p2303crf3: String,
    p2303ct1: String,
    p2303ct2: String,
    p2303ct3: String,
    p2303cc1: String,
    p2303cc2: String,
    p2303cc3: String,
    p2303cp1: String,
    p2303cp2: String,
    p2303cp3: String,

    p2305crf1: String,
    p2305crf2: String,
    p2305crf3: String,
    p2305ct1: String,
    p2305ct2: String,
    p2305ct3: String,
    p2305cc1: String,
    p2305cc2: String,
    p2305cc3: String,
    p2305cp1: String,
    p2305cp2: String,
    p2305cp3: String,

    a2307crf1: String,
    a2307crf2: String,
    a2307crf3: String,
    a2307ct1: String,
    a2307ct2: String,
    a2307ct3: String,
    a2307cc1: String,
    a2307cc2: String,
    a2307cc3: String,
    a2307cp1: String,
    a2307cp2: String,
    a2307cp3: String,

    b2308crf1: String,
    b2308crf2: String,
    b2308crf3: String,
    b2308ct1: String,
    b2308ct2: String,
    b2308ct3: String,
    b2308cc1: String,
    b2308cc2: String,
    b2308cc3: String,
    b2308cp1: String,
    b2308cp2: String,
    b2308cp3: String,

    v2309crf1: String,
    v2309crf2: String,
    v2309crf3: String,
    v2309ct1: String,
    v2309ct2: String,
    v2309ct3: String,
    v2309cc1: String,
    v2309cc2: String,
    v2309cc3: String,
    v2309cp1: String,
    v2309cp2: String,
    v2309cp3: String,

    p2310crf1: String,
    p2310crf2: String,
    p2310crf3: String,
    p2310ct1: String,
    p2310ct2: String,
    p2310ct3: String,
    p2310cc1: String,
    p2310cc2: String,
    p2310cc3: String,
    p2310cp1: String,
    p2310cp2: String,
    p2310cp3: String,

    c2322crf1: String,
    c2322crf2: String,
    c2322crf3: String,
    c2322ct1: String,
    c2322ct2: String,
    c2322ct3: String,
    c2322cc1: String,
    c2322cc2: String,
    c2322cc3: String,
    c2322cp1: String,
    c2322cp2: String,
    c2322cp3: String,

    m2323crf1: String,
    m2323crf2: String,
    m2323crf3: String,
    m2323ct1: String,
    m2323ct2: String,
    m2323ct3: String,
    m2323cc1: String,
    m2323cc2: String,
    m2323cc3: String,
    m2323cp1: String,
    m2323cp2: String,
    m2323cp3: String,

    c2324crf1: String,
    c2324crf2: String,
    c2324crf3: String,
    c2324ct1: String,
    c2324ct2: String,
    c2324ct3: String,
    c2324cc1: String,
    c2324cc2: String,
    c2324cc3: String,
    c2324cp1: String,
    c2324cp2: String,
    c2324cp3: String,

    //Dispositivos de control de contactores

    n3004crf1: String,
    n3004crf2: String,
    n3004crf3: String,
    n3004ct1: String,
    n3004ct2: String,
    n3004ct3: String,
    n3004cc1: String,
    n3004cc2: String,
    n3004cc3: String,
    n3004cp1: String,
    n3004cp2: String,
    n3004cp3: String,

    v3007crf1: String,
    v3007crf2: String,
    v3007crf3: String,
    v3007ct1: String,
    v3007ct2: String,
    v3007ct3: String,
    v3007cc1: String,
    v3007cc2: String,
    v3007cc3: String,
    v3007cp1: String,
    v3007cp2: String,
    v3007cp3: String,

    t3048crf1: String,
    t3048crf2: String,
    t3048crf3: String,
    t3048ct1: String,
    t3048ct2: String,
    t3048ct3: String,
    t3048cc1: String,
    t3048cc2: String,
    t3048cc3: String,
    t3048cp1: String,
    t3048cp2: String,
    t3048cp3: String,

    a3058crf1: String,
    a3058crf2: String,
    a3058crf3: String,
    a3058ct1: String,
    a3058ct2: String,
    a3058ct3: String,
    a3058cc1: String,
    a3058cc2: String,
    a3058cc3: String,
    a3058cp1: String,
    a3058cp2: String,
    a3058cp3: String,

    n3090crf1: String,
    n3090crf2: String,
    n3090crf3: String,
    n3090ct1: String,
    n3090ct2: String,
    n3090ct3: String,
    n3090cc1: String,
    n3090cc2: String,
    n3090cc3: String,
    n3090cp1: String,
    n3090cp2: String,
    n3090cp3: String,

    m3201crf1: String,
    m3201crf2: String,
    m3201crf3: String,
    m3201ct1: String,
    m3201ct2: String,
    m3201ct3: String,
    m3201cc1: String,
    m3201cc2: String,
    m3201cc3: String,
    m3201cp1: String,
    m3201cp2: String,
    m3201cp3: String,

    b3202crf1: String,
    b3202crf2: String,
    b3202crf3: String,
    b3202ct1: String,
    b3202ct2: String,
    b3202ct3: String,
    b3202cc1: String,
    b3202cc2: String,
    b3202cc3: String,
    b3202cp1: String,
    b3202cp2: String,
    b3202cp3: String,

    a3203crf1: String,
    a3203crf2: String,
    a3203crf3: String,
    a3203ct1: String,
    a3203ct2: String,
    a3203ct3: String,
    a3203cc1: String,
    a3203cc2: String,
    a3203cc3: String,
    a3203cp1: String,
    a3203cp2: String,
    a3203cp3: String,

    g3204crf1: String,
    g3204crf2: String,
    g3204crf3: String,
    g3204ct1: String,
    g3204ct2: String,
    g3204ct3: String,
    g3204cc1: String,
    g3204cc2: String,
    g3204cc3: String,
    g3204cp1: String,
    g3204cp2: String,
    g3204cp3: String,

    e3205crf1: String,
    e3205crf2: String,
    e3205crf3: String,
    e3205ct1: String,
    e3205ct2: String,
    e3205ct3: String,
    e3205cc1: String,
    e3205cc2: String,
    e3205cc3: String,
    e3205cp1: String,
    e3205cp2: String,
    e3205cp3: String,

    obs7: String,

    //Contacto Auxiliar de contactores
    ca1crf1: String,
    ca1crf2: String,
    ca1crf3: String,
    ca1ct1: String,
    ca1ct2: String,
    ca1ct3: String,
    ca1cc1: String,
    ca1cc2: String,
    ca1cc3: String,
    ca1cp1: String,
    ca1cp2: String,
    ca1cp3: String,

    ca2crf1: String,
    ca2crf2: String,
    ca2crf3: String,
    ca2ct1: String,
    ca2ct2: String,
    ca2ct3: String,
    ca2cc1: String,
    ca2cc2: String,
    ca2cc3: String,
    ca2cp1: String,
    ca2cp2: String,
    ca2cp3: String,

    ca3crf1: String,
    ca3crf2: String,
    ca3crf3: String,
    ca3ct1: String,
    ca3ct2: String,
    ca3ct3: String,
    ca3cc1: String,
    ca3cc2: String,
    ca3cc3: String,
    ca3cp1: String,
    ca3cp2: String,
    ca3cp3: String,

    ca4crf1: String,
    ca4crf2: String,
    ca4crf3: String,
    ca4ct1: String,
    ca4ct2: String,
    ca4ct3: String,
    ca4cc1: String,
    ca4cc2: String,
    ca4cc3: String,
    ca4cp1: String,
    ca4cp2: String,
    ca4cp3: String,

    dscrf1: String,
    dscrf2: String,
    dscrf3: String,
    dsct1: String,
    dsct2: String,
    dsct3: String,
    dscc1: String,
    dscc2: String,
    dscc3: String,
    dscp1: String,
    dscp2: String,
    dscp3: String,

    dncrf1: String,
    dncrf2: String,
    dncrf3: String,
    dnct1: String,
    dnct2: String,
    dnct3: String,
    dncc1: String,
    dncc2: String,
    dncc3: String,
    dncp1: String,
    dncp2: String,
    dncp3: String,

    plcrf1: String,
    plcrf2: String,
    plcrf3: String,
    plct1: String,
    plct2: String,
    plct3: String,
    plcc1: String,
    plcc2: String,
    plcc3: String,
    plcp1: String,
    plcp2: String,
    plcp3: String,

    secrf1: String,
    secrf2: String,
    secrf3: String,
    sect1: String,
    sect2: String,
    sect3: String,
    secc1: String,
    secc2: String,
    secc3: String,
    secp1: String,
    secp2: String,
    secp3: String,

    arcrf1: String,
    arcrf2: String,
    arcrf3: String,
    arct1: String,
    arct2: String,
    arct3: String,
    arcc1: String,
    arcc2: String,
    arcc3: String,
    arcp1: String,
    arcp2: String,
    arcp3: String,

    cacrf1: String,
    cacrf2: String,
    cacrf3: String,
    cact1: String,
    cact2: String,
    cact3: String,
    cacc1: String,
    cacc2: String,
    cacc3: String,
    cacp1: String,
    cacp2: String,
    cacp3: String,

    //Camara de Arqueo
    apacrf1: String,
    apacrf2: String,
    apacrf3: String,
    apact1: String,
    apact2: String,
    apact3: String,
    apacc1: String,
    apacc2: String,
    apacc3: String,
    apacp1: String,
    apacp2: String,
    apacp3: String,

    obs8: String,

    //Electronica de mando Fila C
    lb03if: String,
    lb03le: String,
    lb03lc: String,

    aiv1gtoif: String,
    aiv1gtole: String,
    aiv1gtolc: String,

    aiv1if: String,
    aiv1le: String,
    aiv1lc: String,

    aiv2if: String,
    aiv2le: String,
    aiv2lc: String,

    asaeif: String,
    asaele: String,
    asaelc: String,

    lb49if: String,
    lb49le: String,
    lb49lc: String,

    sv60if: String,
    sv60le: String,
    sv60lc: String,

    sv24if: String,
    sv24le: String,
    sv24lc: String,

    sv24vif: String,
    sv24vle: String,
    sv24vlc: String,

    sv15if: String,
    sv15le: String,
    sv15lc: String,

    sv15vif: String,
    sv15vle: String,
    sv15vlc: String,

    eshif: String,
    eshle: String,
    eshlc: String,

    //Electronica de mando fila G

    lbc003if: String,
    lbc003le: String,
    lbc003lc: String,

    lbc011if: String,
    lbc011le: String,
    lbc011lc: String,

    zrif: String,
    zrle: String,
    zrlc: String,

    sp27if: String,
    sp27le: String,
    sp27lc: String,

    stssif: String,
    stssle: String,
    stsslc: String,

    wrssif: String,
    wrssle: String,
    wrsslc: String,

    dif1if: String,
    dif1le: String,
    dif1lc: String,

    dif2if: String,
    dif2le: String,
    dif2lc: String,

    aifif: String,
    aifle: String,
    aiflc: String,

    umodif: String,
    umodle: String,
    umodlc: String,

    uwstif: String,
    uwstle: String,
    uwstlc: String,

    mpif: String,
    mple: String,
    mplc: String,

    vavdif: String,
    vavdle: String,
    vavdlc: String,

    istaif: String,
    istale: String,
    istalc: String,

    ebif: String,
    eble: String,
    eblc: String,

    eaif: String,
    eale: String,
    ealc: String,

    lb131if: String,
    lb131le: String,
    lb131lc: String,

    edif: String,
    edle: String,
    edlc: String,

    epzif: String,
    epzle: String,
    epzlc: String,

    lbc155if: String,
    lbc155le: String,
    lbc155lc: String,

    lbc163if: String,
    lbc163le: String,
    lbc163lc: String,

    //Electrica de mando Fila E

    v1v: String,
    v1l: String,
    v1f: String,

    v2v: String,
    v2l: String,
    v2f: String,

    v3v: String,
    v3l: String,
    v3f: String,

    f3v: String,
    f3l: String,
    f3f: String,

    f2v: String,
    f2l: String,
    f2f: String,

    f1v: String,
    f1l: String,
    f1f: String,

    lvv: String,
    lvl: String,
    lvf: String,

    ccv: String,
    ccl: String,
    ccf: String,

    //Rack aparato

    rv: String,
    rl: String,
    rb: String,

    obs9: String,

    //CAP

    vtef: String,
    vtl: String,
    vtpi: String,
    vtaj: String,

    vpef: String,
    vpl: String,
    vppi: String,
    vpaj: String,

    vbef: String,
    vbl: String,
    vbpi: String,
    vbaj: String,

    vtoef: String,
    vtol: String,
    vtopi: String,
    vtoaj: String,

    vcef: String,
    vcl: String,
    vcpi: String,
    vcaj: String,

    meef: String,
    mel: String,
    mepi: String,
    meaj: String,

    mref: String,
    mrl: String,
    mrpi: String,
    mraj: String,

    mroef: String,
    mrol: String,
    mropi: String,
    mroaj: String,

    mvef: String,
    mvl: String,
    mvpi: String,
    mvaj: String,

    mtef: String,
    mtl: String,
    mtpi: String,
    mtaj: String,

    mttef: String,
    mttl: String,
    mttpi: String,
    mttaj: String,

    mccef: String,
    mccl: String,
    mccpi: String,
    mccaj: String,

    mbcef: String,
    mbcl: String,
    mbcpi: String,
    mbcaj: String,

    uv: String,
    vw: String,
    wu: String,
    ut: String,
    vt: String,
    wt: String,
    ai: String,
    ni: String,
    rpm: String,

    //Equipo Utilizado
    equipolUtilizado: {
        numberOfEquipo: Number,    
        arr: [{
            numberOfequ: String,
            marca: String,
            inv: String,
        }]
    },
    
    obs10: String,
    //Materiales
materialUtilizado: {
    numberOfMaterial: Number,    
    arr: [{
        _id: String,
        code: String,
        description: String,
        voucherNumber: String,
        quantity: String,
        unit: String
    }]
},

documentFormCurrentState: {
    approvalByWorker    : { id_worker: String, checked: Boolean },
    approvalBySupervisor: { id_worker: String, checked: Boolean },
    approvalByMannager  : { id_worker: String, checked: Boolean },
    loading: Boolean
},
historyFile: [
    {
        id_worker: String,
        workerName: String,
  
        editDate: Date,
        editValue: Number
    }
]

});

module.exports = mongoose.model('memaM23', memaM23Schema);
